#!/usr/bin/env python3
# apply_defaults_dropdown_fix.py — the admin-UI "Strategy config" dropdown
# was missing FOUR strategies (TMA_V2, VET_V1, BRK_V1, ORB_V1): the
# dropdown lists the keys of license_server/strategy_defaults.json, which
# is generated by gen_strategy_defaults.py and was last regenerated in the
# TSG era. The exact footgun the fleet notes already warn about.
#
# Fence: DEFAULTS_DROPDOWN_20260904
#
# WHAT THIS DOES
#   1. RUNS the generator against THIS tree (single source of truth:
#      DEFAULT_STRATEGY_CONFIGS) and asserts all 16 strategies land,
#      including the four missing ones. ORB's template carries the sealed
#      config minus lots (friend-owned) and minus trade_execution_mode
#      (opt-in lever) — target_value stays, so Config A/B is enforceable
#      fleet-wide from the editor.
#   2. admin_ui.html: staleness guard in ovPopulateSelect — if
#      ALL_STRATEGIES has ids absent from the defaults JSON, the editor
#      shows a loud STALE warning naming them (this class of gap can no
#      longer be silent).
#   3. docs/strategy_checklist.md 2.14: regeneration + droplet redeploy is
#      now part of the license-server row.
#
# AFTER APPLYING: redeploy the droplet (deploy-license-server.command
# ships server.py + admin_ui.html + strategy_defaults.json). No app
# rebuild needed — this is license-server-side only.
#
# USAGE: python3 apply_defaults_dropdown_fix.py --check && python3 apply_defaults_dropdown_fix.py

from __future__ import annotations
import argparse, os, py_compile, shutil, subprocess, sys, tempfile

FENCE = 'DEFAULTS_DROPDOWN_20260904'
ROOT = os.path.dirname(os.path.abspath(__file__))
DESKTOP_BACKEND = os.path.join(ROOT, "desktop", "src-tauri", "backend")

PAYLOADS = {}

EDITS = [('license_server/admin_ui.html', 'before', '    sel.innerHTML = ids.map(sid => `<option value="${sid}">${sid}</option>`).join("");\n', '    /* ── DEFAULTS_DROPDOWN_20260904 ── staleness guard: the dropdown\n       is the JSON\'s keys; ALL_STRATEGIES is the entitlement list. When\n       they diverge the JSON was not regenerated (bit TMA_V2, VET_V1,\n       BRK_V1 and ORB_V1 before this guard existed). */\n    const missing = ALL_STRATEGIES.filter(s => !(s in defs));\n    if (missing.length) {\n      document.getElementById("govErr").textContent =\n        "strategy_defaults.json is STALE — missing: " + missing.join(", ") +\n        ". Run PYTHONPATH=backend python3 license_server/gen_strategy_defaults.py "+\n        "and redeploy.";\n    }\n', 1), ('docs/strategy_checklist.md', 'replace', '| 2.14 | `license_server/admin_ui.html` | `ALL_STRATEGIES` list. **Miss it and every friend on a named-strategy license silently never launches the strategy — an ADMIN `*` license masks this on the dev machine.** Deploys with the license server, not the app. |\n', "| 2.14 | `license_server/admin_ui.html` | `ALL_STRATEGIES` list. **Miss it and every friend on a named-strategy license silently never launches the strategy — an ADMIN `*` license masks this on the dev machine.** Deploys with the license server, not the app. **AND regenerate the config-editor templates (2026-09-04, bit FOUR strategies: TMA_V2/VET/BRK/ORB were absent from the strategy-config dropdown):** `PYTHONPATH=backend python3 license_server/gen_strategy_defaults.py`, then redeploy the droplet (the deploy script ships strategy_defaults.json). The dropdown is the JSON's keys, NOT ALL_STRATEGIES — the UI now shows a stale-defaults warning when they diverge. |\n", 1)]

VERIFY = [('license_server/admin_ui.html', 'DEFAULTS_DROPDOWN_20260904', 1), ('license_server/strategy_defaults.json', '"ORB_V1"', 1), ('license_server/strategy_defaults.json', '"VET_V1"', 1), ('license_server/strategy_defaults.json', '"BRK_V1"', 1), ('license_server/strategy_defaults.json', '"TMA_V2"', 1), ('docs/strategy_checklist.md', 'gen_strategy_defaults.py', 1)]



def fail(msg):
    print(f"  ABORT  {msg}")
    sys.exit(1)


def both_trees(rel, single):
    """A backend-relative path lands in both trees; frontend in one."""
    out = [os.path.join(ROOT, rel)]
    if rel.startswith("backend/") and not single:
        out.append(os.path.join(DESKTOP_BACKEND, rel[len("backend/"):]))
    return out


def stage_edit(text, kind, anchor, payload, count, path):
    n = text.count(anchor)
    if kind == "replaceall":
        if n != count:
            fail(f"{path}: anchor x{n}, expected x{count}: {anchor[:60]!r}")
        return text.replace(anchor, payload)
    if n != count:
        fail(f"{path}: anchor x{n}, expected x{count}: {anchor[:60]!r}")
    if kind == "replace":
        return text.replace(anchor, payload)
    if kind == "before":
        return text.replace(anchor, payload + anchor)
    if kind == "after":
        return text.replace(anchor, anchor + payload)
    fail(f"unknown edit kind {kind}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--single-tree", action="store_true")
    a = ap.parse_args()

    if not os.path.isdir(os.path.join(ROOT, "backend", "app")):
        fail("run this from the scalp-app repo root")
    if not a.single_tree and not os.path.isdir(DESKTOP_BACKEND):
        fail("desktop/src-tauri/backend missing — dual-tree is a hard "
             "requirement locally; pass --single-tree only on a CI checkout")

    # ── regenerate the defaults JSON from THIS tree first ──
    gen = os.path.join(ROOT, "license_server", "gen_strategy_defaults.py")
    if not os.path.exists(gen):
        fail("gen_strategy_defaults.py not found — run from the repo root")
    env = dict(os.environ, PYTHONPATH=os.path.join(ROOT, "backend"))
    r = subprocess.run([sys.executable, gen], env=env,
                       capture_output=True, text=True)
    if r.returncode != 0:
        fail(f"generator failed: {r.stderr.strip()[-400:]}")
    print(f"  GEN    {r.stdout.strip()}")
    import json as _json
    defs = _json.load(open(os.path.join(ROOT, "license_server",
                                        "strategy_defaults.json")))
    need = {"TMA_V2", "VET_V1", "BRK_V1", "ORB_V1"}
    missing = sorted(need - set(defs))
    if missing:
        fail(f"regenerated defaults still missing {missing} — is the "
             f"strategy in DEFAULT_STRATEGY_CONFIGS?")
    print(f"  OK     defaults JSON: {len(defs)} strategies incl. "
          f"{sorted(need)}")

    # ── idempotency ──
    probe = os.path.join(ROOT, "license_server", "admin_ui.html")
    if FENCE in open(probe, encoding="utf-8").read():
        print(f"  SKIP   dropdown guard already present (defaults regenerated above) — "
              f"nothing to do")
        return

    # ── stage every write in memory first ──
    staged = {}   # abs path -> new text
    for rel, body in PAYLOADS.items():
        for p in both_trees(rel, a.single_tree):
            if os.path.exists(p):
                fail(f"{p} already exists (half-applied tree?)")
            staged[p] = body
    per_file = {}
    for rel, kind, anchor, payload, count in EDITS:
        per_file.setdefault(rel, []).append((kind, anchor, payload, count))
    for rel, ops in per_file.items():
        src_path = os.path.join(ROOT, rel)
        if not os.path.exists(src_path):
            fail(f"{src_path} not found")
        text = open(src_path, encoding="utf-8").read()
        if FENCE in text:
            fail(f"{rel} already carries the fence — mixed state, resolve by hand")
        for kind, anchor, payload, count in ops:
            text = stage_edit(text, kind, anchor, payload, count, rel)
        for p in both_trees(rel, a.single_tree):
            if p != src_path and not os.path.exists(p):
                fail(f"dual-tree copy missing: {p}")
            staged[p] = text

    print(f"  OK     all anchors verified ({len(staged)} file writes staged)")

    # ── staged compile gates ──
    tmp = tempfile.mkdtemp(prefix="orv_gate_")
    jsx_targets = []
    for p, body in staged.items():
        t = os.path.join(tmp, os.path.basename(p))
        with open(t, "w", encoding="utf-8") as f:
            f.write(body)
        if p.endswith(".py"):
            try:
                py_compile.compile(t, doraise=True)
            except py_compile.PyCompileError as e:
                fail(f"py_compile gate: {p}: {e}")
        elif p.endswith((".jsx", ".js")):
            jsx_targets.append((p, t))
    print(f"  OK     py_compile gate passed")
    esb = shutil.which("esbuild")
    npx = shutil.which("npx")
    for p, t in jsx_targets:
        cmd = None
        if esb:
            cmd = [esb, "--loader:.jsx=jsx", "--loader:.js=jsx", t, "--outfile=/dev/null"]
        elif npx:
            cmd = [npx, "--yes", "esbuild", "--loader:.jsx=jsx", "--loader:.js=jsx", t, "--outfile=/dev/null"]
        if cmd is None:
            print(f"  WARN   esbuild unavailable — JSX gate skipped for {p}")
            continue
        r = subprocess.run(cmd, capture_output=True, text=True,
                           cwd=os.path.join(ROOT, "frontend"))
        if r.returncode != 0:
            fail(f"esbuild gate: {p}:\n{r.stderr[-2000:]}")
    if jsx_targets and (esb or npx):
        print(f"  OK     esbuild JSX gate passed ({len(jsx_targets)} files)")

    if a.check:
        for p in sorted(staged):
            print(f"  WOULD  write {p}")
        print("  CHECK  dry run complete — no files written")
        return

    # ── write, with backups for edited files ──
    for p, body in sorted(staged.items()):
        os.makedirs(os.path.dirname(p), exist_ok=True)
        if os.path.exists(p):
            shutil.copy2(p, p + f".bak-{FENCE}")
        with open(p, "w", encoding="utf-8") as f:
            f.write(body)
        print(f"  WROTE  {p}")

    # ── grep-count verification ──
    bad = 0
    for rel, needle, mn in VERIFY:
        got = open(os.path.join(ROOT, rel), encoding="utf-8").read().count(needle)
        ok = got >= mn
        print(f"  {'OK ' if ok else 'BAD'}    {rel}: {needle!r} x{got} (need >= {mn})")
        bad += 0 if ok else 1
    if bad:
        fail(f"{bad} verification(s) failed — restore from .bak-{FENCE}")

    print()
    print(f"  DONE   dropdown fixed + guard installed. Next:")
    print(f"         cd backend && PYTHONPATH=$PWD bash license_server/deploy-license-server.command   # ships json+html+server.py to the droplet")
    print(f"         (expect ALL CHECKS PASSED incl. the integration block)")


if __name__ == "__main__":
    main()
