#!/usr/bin/env python3
# apply_lot_comp_dd.py — fence LOT_COMP_DD_20260924 (requires LOT_COMP_EQ_20260924)
#
# Drawdown guard for lot compounding, both modes, hard drop to base:
#   lot_comp_dd_limit_pct  — % of the equity PEAK. Equity = base lots ×
#   capital_per_lot + realised net of trades closed before the day. When
#   equity sits at least this far below its peak, lots are min(rule, base)
#   until equity makes a NEW high; then normal sizing resumes. Calendar mode
#   needs lot_comp_capital_per_lot as the guard's denominator (the form shows
#   the field when a DD % is set). Unset / 0 / ≥100 = off, byte-identical.
#   Lives entirely in engine/lot_compounding.py (begin_day is already wired
#   into every runner) — no runner edits.
#
# Run ONLY this script:
#   cd /Users/anbu/dev/scalp-app && python3 apply_lot_comp_dd.py [--allow-dirty] [--skip-tests]
from __future__ import annotations

import base64
import os
import py_compile
import shutil
import subprocess
import sys
import tempfile

FENCE = "LOT_COMP_DD_20260924"
ROOT = os.path.dirname(os.path.abspath(__file__))
ALLOW_DIRTY = "--allow-dirty" in sys.argv
SKIP_TESTS = "--skip-tests" in sys.argv

BACKEND = "backend/app/backtest"
DESKTOP_BACKEND = "desktop/src-tauri/backend/app/backtest"
FRONTEND = "frontend/src/pages"
DESKTOP_FRONTEND = "desktop/src-tauri/frontend/src/pages"

PREREQ = {
    f"{BACKEND}/engine/lot_compounding.py": "LOT_COMP_EQ_20260924",
    f"{FRONTEND}/Backtest.jsx": "LOT_COMP_EQ_20260924",
    f"{FRONTEND}/backtest/lotCompounding.js": "LOT_COMP_EQ_20260924",
    f"{FRONTEND}/backtest/SweepBuilder.jsx": "LOT_COMP_EQ_20260924",
}
PAYLOADS_B64 = {f"{BACKEND}/engine/test_lot_comp_dd.py": "IyBiYWNrZW5kL2FwcC9iYWNrdGVzdC9lbmdpbmUvdGVzdF9sb3RfY29tcF9kZC5weQojCiMg4pSA4pSAIExPVF9DT01QX0REXzIwMjYwOTI0IOKUgOKUgCBzdGFuZGFsb25lOgojICAgY2QgYmFja2VuZCAmJiBweXRob24zIGFwcC9iYWNrdGVzdC9lbmdpbmUvdGVzdF9sb3RfY29tcF9kZC5weQojIERyYXdkb3duIGd1YXJkOiB3aGVuIGVxdWl0eSAoYmFzZSDDlyBjcGwgKyByZWFsaXNlZCBuZXQpIHNpdHMgbW9yZSB0aGFuCiMgYGxvdF9jb21wX2RkX2xpbWl0X3BjdGAgYmVsb3cgaXRzIHBlYWssIGxvdHMgZHJvcCB0byBCQVNFIChuZXZlciBhYm92ZSBpdCkKIyB1bnRpbCBlcXVpdHkgbWFrZXMgYSBuZXcgaGlnaC4gVW5pdCBjaGVja3Mgb24gdGhlIHN0YXRlIG1hY2hpbmUsIHRoZW4KIyBydW5uZXIgY2hlY2tzIHdoZXJlIGVhY2ggdHJhZGUncyBxdHkgaXMgcmVjb21wdXRlZCBpbmRlcGVuZGVudGx5IGZyb20gdGhlCiMgdHJhZGVzIGNsb3NlZCBiZWZvcmUgaXRzIGVudHJ5IGRheSwgZ3VhcmQgaW5jbHVkZWQuCmZyb20gX19mdXR1cmVfXyBpbXBvcnQgYW5ub3RhdGlvbnMKCmltcG9ydCBvcwppbXBvcnQgc3lzCmZyb20gZGF0ZXRpbWUgaW1wb3J0IGRhdGUKCkhFUkUgPSBvcy5wYXRoLmRpcm5hbWUob3MucGF0aC5hYnNwYXRoKF9fZmlsZV9fKSkKc3lzLnBhdGguaW5zZXJ0KDAsIG9zLnBhdGguYWJzcGF0aChvcy5wYXRoLmpvaW4oSEVSRSwgIi4uIiwgIi4uIiwgIi4uIikpKQpvcy5lbnZpcm9uLnNldGRlZmF1bHQoIlNDQUxQX0xPVF9TSVpFX09GRkxJTkUiLCAiMSIpCgpmcm9tIGFwcC5iYWNrdGVzdC5lbmdpbmUubG90X2NvbXBvdW5kaW5nIGltcG9ydCBMb3RDb21wb3VuZGVyLCBfdHJhZGVfbmV0ICAgIyBub3FhOiBFNDAyCgpGQUlMUyA9IFtdCgoKZGVmIGNoZWNrKG5hbWUsIG9rLCBub3RlPSIiKToKICAgIHByaW50KGYiICB7J1BBU1MnIGlmIG9rIGVsc2UgJ0ZBSUwnfSAge25hbWV9eygnICDigJQgJyArIHN0cihub3RlKSkgaWYgKG5vdGUgYW5kIG5vdCBvaykgZWxzZSAnJ30iKQogICAgaWYgbm90IG9rOgogICAgICAgIEZBSUxTLmFwcGVuZChuYW1lKQoKCmNsYXNzIFQ6CiAgICBkZWYgX19pbml0X18oc2VsZiwgZXhpdF90cywgbmV0X3BubCwgZXhpdF9wcmljZT0xLjApOgogICAgICAgIHNlbGYuZXhpdF90cywgc2VsZi5uZXRfcG5sLCBzZWxmLmV4aXRfcHJpY2UgPSBleGl0X3RzLCBuZXRfcG5sLCBleGl0X3ByaWNlCgoKUyA9IGRhdGUoMjAyMCwgMSwgMSkKRVEgPSB7ImxvdF9jb21wX21vZGUiOiAiZXF1aXR5IiwgImxvdF9jb21wX2NhcGl0YWxfcGVyX2xvdCI6IDEwMDAwMCwgImxvdF9jb21wX21heF9sb3RzIjogMzB9CgpwcmludCgi4pSA4pSAIHBhcnNlIOKUgOKUgCIpCmMgPSBMb3RDb21wb3VuZGVyKHsqKkVRLCAibG90X2NvbXBfZGRfbGltaXRfcGN0IjogMTB9LCBTLCAxMCkKY2hlY2soImRkX2xpbWl0IHBhcnNlZCBhcyBmcmFjdGlvbiIsIGFicyhjLmRkX2xpbWl0IC0gMC4xMCkgPCAxZS0xMikKY2hlY2soImFic2VudCDihpIgMCIsIExvdENvbXBvdW5kZXIoRVEsIFMsIDEwKS5kZF9saW1pdCA9PSAwKQpjaGVjaygic3RyaW5nIGFjY2VwdGVkIiwgYWJzKExvdENvbXBvdW5kZXIoeyoqRVEsICJsb3RfY29tcF9kZF9saW1pdF9wY3QiOiAiMTIuNSJ9LCBTLCAxMCkuZGRfbGltaXQgLSAwLjEyNSkgPCAxZS0xMikKY2hlY2soIuKJpTEwMCDihpIgb2ZmIiwgTG90Q29tcG91bmRlcih7KipFUSwgImxvdF9jb21wX2RkX2xpbWl0X3BjdCI6IDEwMH0sIFMsIDEwKS5kZF9saW1pdCA9PSAwKQpjaGVjaygibmVnYXRpdmUg4oaSIG9mZiIsIExvdENvbXBvdW5kZXIoeyoqRVEsICJsb3RfY29tcF9kZF9saW1pdF9wY3QiOiAtNX0sIFMsIDEwKS5kZF9saW1pdCA9PSAwKQpjaGVjaygianVuayDihpIgb2ZmIiwgTG90Q29tcG91bmRlcih7KipFUSwgImxvdF9jb21wX2RkX2xpbWl0X3BjdCI6ICJ4In0sIFMsIDEwKS5kZF9saW1pdCA9PSAwKQpjaGVjaygiZ3VhcmQgaW5lcnQgd2l0aG91dCBjcGwgKGNhbGVuZGFyLCBubyBjcGwpIiwKICAgICAgbm90IExvdENvbXBvdW5kZXIoeyJsb3RfY29tcF9zdGVwX21vbnRocyI6IDMsICJsb3RfY29tcF9hZGRfbG90cyI6IDEsICJsb3RfY29tcF9kZF9saW1pdF9wY3QiOiAxMH0sIFMsIDEwKS5kZF9ndWFyZF9vbikKY2hlY2soImd1YXJkIGFybWVkIGluIGNhbGVuZGFyIG1vZGUgV0lUSCBjcGwiLAogICAgICBMb3RDb21wb3VuZGVyKHsibG90X2NvbXBfc3RlcF9tb250aHMiOiAzLCAibG90X2NvbXBfYWRkX2xvdHMiOiAxLCAibG90X2NvbXBfZGRfbGltaXRfcGN0IjogMTAsICJsb3RfY29tcF9jYXBpdGFsX3Blcl9sb3QiOiAxMDAwMDB9LCBTLCAxMCkuZGRfZ3VhcmRfb24pCmNoZWNrKCJndWFyZCBhcm1lZCBpbiBlcXVpdHkgbW9kZSIsIGMuZGRfZ3VhcmRfb24pCgpwcmludCgi4pSA4pSAIGVxdWl0eSBtb2RlIHN0YXRlIG1hY2hpbmUgKHN0YXJ0IOKCuTEwTCwgbGltaXQgMTAlKSDilIDilIAiKQpEID0gbGFtYmRhIG46IGRhdGUoMjAyMCwgMSwgbikgICAjIG5vcWE6IEU3MzEKdHIgPSBbXQpjaGVjaygiZGF5IDE6IGJhc2UsIGd1YXJkIGlkbGUiLCBjLmJlZ2luX2RheShEKDEpLCB0cikgPT0gMTAgYW5kIG5vdCBjLmRkX2FjdGl2ZSkKdHIuYXBwZW5kKFQoMSwgKzMwMDAwMCkpICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIyBlcXVpdHkgMTNMIOKGkiAxMyBsb3RzCmNoZWNrKCJkYXkgMjogMTMgbG90cyAocGVhayAxM0wpIiwgYy5iZWdpbl9kYXkoRCgyKSwgdHIpID09IDEzIGFuZCBjLmRkX3BlYWsgPT0gMTMwMDAwMCkKdHIuYXBwZW5kKFQoMiwgLTEyMDAwMCkpICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIyBlcXVpdHkgMTEuOEwsIEREIDkuMiUg4oaSIHN0aWxsIHNpemVkIDExCmNoZWNrKCJkYXkgMzogREQgOS4yJSA8IDEwJSDihpIgMTEgbG90cywgZ3VhcmQgaWRsZSIsIGMuYmVnaW5fZGF5KEQoMyksIHRyKSA9PSAxMSBhbmQgbm90IGMuZGRfYWN0aXZlKQp0ci5hcHBlbmQoVCgzLCAtMjAwMDApKSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAjIGVxdWl0eSAxMS42TCwgREQgMTAuOCUg4oaSIGJyZWFjaApjaGVjaygiZGF5IDQ6IEREIDEwLjglIOKJpSAxMCUg4oaSIEJSRUFDSCDihpIgYmFzZSAxMCAobm90IDExKSIsIGMuYmVnaW5fZGF5KEQoNCksIHRyKSA9PSAxMCBhbmQgYy5kZF9hY3RpdmUpCmNoZWNrKCJsb3RzKCkgcmVwb3J0cyBndWFyZGVkIGxvdHMiLCBjLmxvdHMoRCg0KSkgPT0gMTAgYW5kIGMubXVsdChEKDQpKSA9PSAxLjApCnRyLmFwcGVuZChUKDQsICs1MDAwMCkpICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICMgZXF1aXR5IDEyLjFMLCBzdGlsbCBiZWxvdyAxM0wgcGVhawpjaGVjaygiZGF5IDU6IHBhcnRpYWwgcmVjb3Zlcnkg4oaSIHN0aWxsIGJhc2UiLCBjLmJlZ2luX2RheShEKDUpLCB0cikgPT0gMTAgYW5kIGMuZGRfYWN0aXZlKQp0ci5hcHBlbmQoVCg1LCAtNDAwMDAwKSkgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAjIGVxdWl0eSA4LjFMIOKGkiBlcXVpdHkgcnVsZSBzYXlzIDgKY2hlY2soImRheSA2OiBkZWVwIEREIOKGkiBndWFyZCBrZWVwcyBtaW4ocnVsZSwgYmFzZSkgPSA4IiwgYy5iZWdpbl9kYXkoRCg2KSwgdHIpID09IDggYW5kIGMuZGRfYWN0aXZlKQp0ci5hcHBlbmQoVCg2LCArNDgwMDAwKSkgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAjIGVxdWl0eSAxMi45TCwganVzdCB1bmRlciBwZWFrCmNoZWNrKCJkYXkgNzogdW5kZXIgdGhlIG9sZCBwZWFrIOKGkiBzdGlsbCBndWFyZGVkICgxMiDihpIgMTApIiwgYy5iZWdpbl9kYXkoRCg3KSwgdHIpID09IDEwIGFuZCBjLmRkX2FjdGl2ZSkKdHIuYXBwZW5kKFQoNywgKzE1MDAwMCkpICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIyBlcXVpdHkgMTQuNEwg4oaSIG5ldyBoaWdoCmNoZWNrKCJkYXkgODogbmV3IGVxdWl0eSBoaWdoIOKGkiBndWFyZCBvZmYg4oaSIDE0IGxvdHMiLCBjLmJlZ2luX2RheShEKDgpLCB0cikgPT0gMTQgYW5kIG5vdCBjLmRkX2FjdGl2ZSBhbmQgYy5kZF9wZWFrID09IDE0NDAwMDApCmRnID0gYy5kaWFnKCkKY2hlY2soImRpYWcgcmVjb3JkcyBicmVhY2ggKyByZWNvdmVyeSIsIGRnWyJkZF9ndWFyZCJdWyJsaW1pdF9wY3QiXSA9PSAxMCBhbmQgW2VbInR5cGUiXSBmb3IgZSBpbiBkZ1siZGRfZ3VhcmQiXVsiZXZlbnRzIl1dID09IFsiYnJlYWNoIiwgInJlY292ZXIiXSkKY2hlY2soImRpYWcgZ3VhcmRlZC1kYXkgY291bnQgPSA0IChkYXlzIDQtNykiLCBkZ1siZGRfZ3VhcmQiXVsiZGF5cyJdID09IDQpCmNoZWNrKCJsYWRkZXIgc2hvd3MgZWZmZWN0aXZlIGxvdHMiLCBbbiBmb3IgXywgbiBpbiBjLl9lcV9sYWRkZXJdID09IFsxMCwgMTMsIDExLCAxMCwgOCwgMTAsIDE0XSkKY2hlY2soImRlc2NyaWJlIG1lbnRpb25zIGRkIiwgImRkPTEwJSIgaW4gYy5kZXNjcmliZSgpKQoKcHJpbnQoIuKUgOKUgCBjYWxlbmRhciBtb2RlIGd1YXJkICgxMCDihpIgKzEvMW1vLCBjcGwg4oK5MUwsIGxpbWl0IDEwJSkg4pSA4pSAIikKayA9IExvdENvbXBvdW5kZXIoeyJsb3RfY29tcF9zdGVwX21vbnRocyI6IDEsICJsb3RfY29tcF9hZGRfbG90cyI6IDEsICJsb3RfY29tcF9kZF9saW1pdF9wY3QiOiAxMCwgImxvdF9jb21wX2NhcGl0YWxfcGVyX2xvdCI6IDEwMDAwMH0sIFMsIDEwKQp0ciA9IFtdCmNoZWNrKCJKYW46IGxhZGRlciAxMCIsIGsuYmVnaW5fZGF5KGRhdGUoMjAyMCwgMSwgMiksIHRyKSA9PSAxMCkKY2hlY2soIkZlYjogbGFkZGVyIDExIiwgay5iZWdpbl9kYXkoZGF0ZSgyMDIwLCAyLCAzKSwgdHIpID09IDExKQp0ci5hcHBlbmQoVCgxLCAtMTUwMDAwKSkgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIyBlcXVpdHkgOC41TCB2cyBwZWFrIDEwTCDihpIgREQgMTUlCmNoZWNrKCJNYXIgYWZ0ZXIg4oiSMTUlOiBicmVhY2gg4oaSIGJhc2UgMTAgKGxhZGRlciB3b3VsZCBiZSAxMikiLCBrLmJlZ2luX2RheShkYXRlKDIwMjAsIDMsIDIpLCB0cikgPT0gMTAgYW5kIGsuZGRfYWN0aXZlKQpjaGVjaygidGllciBzdGlsbCBhZHZhbmNlcyB1bmRlcm5lYXRoIiwgay50aWVyKGRhdGUoMjAyMCwgMywgMikpID09IDIpCnRyLmFwcGVuZChUKDIsICsyMDAwMDApKSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAjIGVxdWl0eSAxMC41TCDihpIgbmV3IGhpZ2gKY2hlY2soIkFwciBhZnRlciBuZXcgaGlnaDogbGFkZGVyIDEzIHJlc3VtZXMiLCBrLmJlZ2luX2RheShkYXRlKDIwMjAsIDQsIDEpLCB0cikgPT0gMTMgYW5kIG5vdCBrLmRkX2FjdGl2ZSkKb2ZmID0gTG90Q29tcG91bmRlcih7ImxvdF9jb21wX3N0ZXBfbW9udGhzIjogMSwgImxvdF9jb21wX2FkZF9sb3RzIjogMX0sIFMsIDEwKQpjaGVjaygibm8gZ3VhcmQ6IGJlZ2luX2RheSBpcyBzdGlsbCBhIG5vLW9wIGZvciBjYWxlbmRhciIsIG9mZi5iZWdpbl9kYXkoZGF0ZSgyMDIwLCA0LCAxKSwgdHIpID09IDEzIGFuZCBub3Qgb2ZmLmRkX2d1YXJkX29uKQoKIyDilIDilIAgcnVubmVycyDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAKcHJpbnQoIuKUgOKUgCBydW5uZXJzIOKUgOKUgCIpCnRyeToKICAgIHNyYyA9IG9wZW4ob3MucGF0aC5qb2luKEhFUkUsICJ0ZXN0X2xvdF9jb21wX3J1bm5lcnMucHkiKSwgZW5jb2Rpbmc9InV0Zi04IikucmVhZCgpCiAgICBoZWFkID0gc3JjLnNwbGl0KCJSVU5ORVJTID0gWyIpWzBdLnJlcGxhY2UoIndoaWxlIGxlbihhbGxfZGF5cykgPCA0NToiLCAid2hpbGUgbGVuKGFsbF9kYXlzKSA8IDMwOiIpCiAgICBucyA9IHsiX19maWxlX18iOiBvcy5wYXRoLmpvaW4oSEVSRSwgInRlc3RfbG90X2NvbXBfcnVubmVycy5weSIpLCAiX19uYW1lX18iOiAiX2xjcl9oZWFkIn0KICAgIGV4ZWMoY29tcGlsZShoZWFkLCAibGNyX2hlYWQiLCAiZXhlYyIpLCBucykKICAgIHJ1bl9vbmUsIF9nLCBkYXlfb2ZfdHMsIFJVTl9GUk9NID0gbnNbInJ1bl9vbmUiXSwgbnNbIl9nIl0sIG5zWyJkYXlfb2ZfdHMiXSwgbnNbIlJVTl9GUk9NIl0KICAgIExPVCA9IDY1CgogICAgZGVmIHZlcmlmeShuYW1lLCBjZmcsIHdhbnRfYnJlYWNoPVRydWUpOgogICAgICAgIHIgPSBydW5fb25lKG5hbWUsIGNmZykKICAgICAgICB0ciA9IHJbInRyYWRlcyJdCiAgICAgICAgcmVmID0gTG90Q29tcG91bmRlcihjZmcsIFJVTl9GUk9NLCAxMCkKICAgICAgICBjbG9zZWQgPSBbdCBmb3IgdCBpbiB0ciBpZiBfZyh0LCAiZXhpdF90cyIpIGlzIG5vdCBOb25lIGFuZCBfZyh0LCAiZXhpdF9wcmljZSIpIGlzIG5vdCBOb25lXQogICAgICAgICMgcmVwbGF5IHRoZSBtb2R1bGUgb3ZlciBFVkVSWSBzaW0gZGF5IChhIG5vLWVudHJ5IGRheSBjYW4gc3RpbGwgc2V0IGEKICAgICAgICAjIG5ldyBlcXVpdHkgcGVhayBvciBicmVhY2gpIG9uIHRoZSBjbG9zZWQtYmVmb3JlLWRheSBzdWJzZXRzCiAgICAgICAgZXhwID0ge30KICAgICAgICBmb3IgZCBpbiBbeCBmb3IgeCBpbiBuc1siYWxsX2RheXMiXSBpZiB4ID49IFJVTl9GUk9NXToKICAgICAgICAgICAgYmVmb3JlID0gW3QgZm9yIHQgaW4gY2xvc2VkIGlmIGRheV9vZl90cyhfZyh0LCAiZXhpdF90cyIpKSA8IGRdCiAgICAgICAgICAgIGV4cFtkXSA9IHJlZi5iZWdpbl9kYXkoZCwgYmVmb3JlKQogICAgICAgIGJhZCA9IFsoZGF5X29mX3RzKF9nKHQsICJlbnRyeV90cyIpKSwgaW50KF9nKHQsICJxdHkiKSksIGV4cFtkYXlfb2ZfdHMoX2codCwgImVudHJ5X3RzIikpXSAqIExPVCkKICAgICAgICAgICAgICAgZm9yIHQgaW4gdHIgaWYgaW50KF9nKHQsICJxdHkiKSBvciAwKSAhPSBleHBbZGF5X29mX3RzKF9nKHQsICJlbnRyeV90cyIpKV0gKiBMT1RdCiAgICAgICAgZXYgPSByZWYuZGlhZygpLmdldCgiZGRfZ3VhcmQiLCB7fSkuZ2V0KCJldmVudHMiLCBbXSkKICAgICAgICBicmVhY2hlcyA9IFtlIGZvciBlIGluIGV2IGlmIGVbInR5cGUiXSA9PSAiYnJlYWNoIl0KICAgICAgICBjaGVjayhmIntuYW1lfTogZXZlcnkgdHJhZGUgc2l6ZWQgcGVyIHRoZSBndWFyZGVkIHJ1bGUgKHtsZW4odHIpfSB0cmFkZXMsIHtsZW4oYnJlYWNoZXMpfSBicmVhY2goZXMpLCB7cmVmLmRpYWcoKS5nZXQoJ2RkX2d1YXJkJywge30pLmdldCgnZGF5cycsIDApfSBndWFyZGVkIGRheXMpIiwKICAgICAgICAgICAgICB0ciBhbmQgbm90IGJhZCwgYmFkWzozXSkKICAgICAgICBpZiB3YW50X2JyZWFjaDoKICAgICAgICAgICAgY2hlY2soZiJ7bmFtZX06IGd1YXJkIGFjdHVhbGx5IGZpcmVkIGluIHRoaXMgcnVuIChub3QgdmFjdW91cykiLCBsZW4oYnJlYWNoZXMpID4gMCkKICAgICAgICByZXR1cm4gcmVmCgogICAgRVFEID0geyJsb3RfY29tcF9tb2RlIjogImVxdWl0eSIsICJsb3RfY29tcF9jYXBpdGFsX3Blcl9sb3QiOiAyMDAwMCwgImxvdF9jb21wX21heF9sb3RzIjogMzAsICJsb3RfY29tcF9kZF9saW1pdF9wY3QiOiA1fQogICAgZm9yIG5hbWUgaW4gWyJTVEZDX1YxIiwgIlRTR19WMSIsICJUTUFfVjIiLCAiU0NBTFBfVjEiLCAiVkVUX1YxIiwgIkhBX1YxIl06CiAgICAgICAgdHJ5OgogICAgICAgICAgICB2ZXJpZnkobmFtZSwgRVFEKQogICAgICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgZToKICAgICAgICAgICAgY2hlY2soZiJ7bmFtZX06IHJ1biBleGVjdXRlcyIsIEZhbHNlLCByZXByKGUpKQogICAgQ0FMRCA9IHsibG90X2NvbXBfc3RlcF9tb250aHMiOiAxLCAibG90X2NvbXBfYWRkX2xvdHMiOiAxMCwgImxvdF9jb21wX2NhcGl0YWxfcGVyX2xvdCI6IDIwMDAwLCAibG90X2NvbXBfZGRfbGltaXRfcGN0IjogNX0KICAgIGZvciBuYW1lIGluIFsiT1JCX1YxIiwgIklDX1YxIl06CiAgICAgICAgdHJ5OgogICAgICAgICAgICB2ZXJpZnkobmFtZSwgQ0FMRCwgd2FudF9icmVhY2g9KG5hbWUgIT0gIk9SQl9WMSIpKSAgICMgT1JCIG9ubHkgZ2FpbnMgb24gdGhpcyBjb3JwdXMKICAgICAgICBleGNlcHQgRXhjZXB0aW9uIGFzIGU6CiAgICAgICAgICAgIGNoZWNrKGYie25hbWV9OiBjYWxlbmRhcitndWFyZCBydW4gZXhlY3V0ZXMiLCBGYWxzZSwgcmVwcihlKSkKICAgICMgZ3VhcmQgT0ZGIOKJoSB0aGUgZXF1aXR5IHJ1biBvZiB0aGUgcGFyZW50IHN1aXRlIChubyBiZWhhdmlvdXIgY2hhbmdlIHdoZW4gdW5zZXQpCiAgICBhID0gcnVuX29uZSgiU1RGQ19WMSIsIHsibG90X2NvbXBfbW9kZSI6ICJlcXVpdHkiLCAibG90X2NvbXBfY2FwaXRhbF9wZXJfbG90IjogMjAwMDAsICJsb3RfY29tcF9tYXhfbG90cyI6IDMwfSkKICAgIGIgPSBydW5fb25lKCJTVEZDX1YxIiwgeyJsb3RfY29tcF9tb2RlIjogImVxdWl0eSIsICJsb3RfY29tcF9jYXBpdGFsX3Blcl9sb3QiOiAyMDAwMCwgImxvdF9jb21wX21heF9sb3RzIjogMzAsICJsb3RfY29tcF9kZF9saW1pdF9wY3QiOiAwfSkKICAgIGNoZWNrKCJTVEZDOiBkZF9saW1pdCAwIOKJoSB1bnNldCIsIFtpbnQoX2codCwgInF0eSIpKSBmb3IgdCBpbiBhWyJ0cmFkZXMiXV0gPT0gW2ludChfZyh0LCAicXR5IikpIGZvciB0IGluIGJbInRyYWRlcyJdXSkKZXhjZXB0IEV4Y2VwdGlvbiBhcyBlOgogICAgaW1wb3J0IHRyYWNlYmFjawogICAgdHJhY2ViYWNrLnByaW50X2V4YygpCiAgICBjaGVjaygicnVubmVyIGNoZWNrcyBleGVjdXRlIiwgRmFsc2UsIHJlcHIoZSkpCgpwcmludCgpCmlmIEZBSUxTOgogICAgcHJpbnQoZiJGQUlMRUQge2xlbihGQUlMUyl9OiIpCiAgICBmb3IgeCBpbiBGQUlMUzoKICAgICAgICBwcmludCgiICAtIiwgeCkKICAgIHN5cy5leGl0KDEpCnByaW50KCJBTEwgTE9UX0NPTVBfREQgQ0hFQ0tTIFBBU1NFRCIpCg=="}
FRAG_B64 = {"lco_old": "ZXhwb3J0IGZ1bmN0aW9uIGxvdENvbXBPZihjZmcsIGRhdGVGcm9tLCBkYXRlVG8sIHN1bW1hcnkpIHsKICBjb25zdCBiYXNlID0gYmFzZUxvdHNPZihjZmcpOwogIGNvbnN0IG1vZGUgPSBsb3RDb21wTW9kZShjZmcpOwogIGNvbnN0IGNwbCA9IE51bWJlcihjZmc/LmxvdF9jb21wX2NhcGl0YWxfcGVyX2xvdCkgfHwgMDsKICBjb25zdCBwID0gbG90Q29tcFBhcnNlKGNmZyk7CiAgaWYgKG1vZGUgPT09ICJlcXVpdHkiID8gIShiYXNlID4gMCAmJiBjcGwgPiAwKSA6ICFwKSByZXR1cm4gbnVsbDsKICBjb25zdCByYXdNYXggPSBNYXRoLmZsb29yKE51bWJlcihjZmc/LmxvdF9jb21wX21heF9sb3RzKSkgfHwgMDsKICBjb25zdCBtYXggPSBiYXNlICE9IG51bGwgJiYgcmF3TWF4ID49IGJhc2UgPyByYXdNYXggOiAwOwogIGNvbnN0IHNjYWxlUnMgPSAhKGNmZz8ubG90X2NvbXBfc2NhbGVfcnMgPT09IGZhbHNlIHx8IFN0cmluZyhjZmc/LmxvdF9jb21wX3NjYWxlX3JzKS50b0xvd2VyQ2FzZSgpID09PSAiZmFsc2UiKTsKICBjb25zdCBjYXBMb3RzID0gKG4pID0+IChtYXggPyBNYXRoLm1pbihuLCBtYXgpIDogbik7CiAgLy8gYWN0dWFsIHBlYWsgZnJvbSB0aGUgcGVyc2lzdGVkIHJ1biwgd2hlbiB3ZSBoYXZlIGl0CiAgY29uc3QgbHMgPSBsb3RTaXplT2YoY2ZnLCB1bmRlZmluZWQsIGNmZz8udW5kZXJseWluZyk7CiAgY29uc3QgYWN0dWFsUGVhayA9IHN1bW1hcnkgJiYgTnVtYmVyKHN1bW1hcnkucXR5X21heCkgPiAwICYmIGxzID8gTWF0aC5yb3VuZChOdW1iZXIoc3VtbWFyeS5xdHlfbWF4KSAvIGxzKSA6IG51bGw7CiAgaWYgKG1vZGUgPT09ICJlcXVpdHkiKSB7CiAgICBjb25zdCBwZWFrID0gYWN0dWFsUGVhayA/PyBiYXNlOwogICAgY29uc3QgdGFnID0gYEVxdWl0eSDigrkke2ZtdEwoY3BsKX1ML2xvdCR7bWF4ID8gYCDiiaQke21heH1MYCA6ICIifSR7c2NhbGVScyA/ICIiIDogIiDCtyDigrkgZml4ZWQifWA7CiAgICBjb25zdCBsYWJlbCA9IGFjdHVhbFBlYWsgIT0gbnVsbCA/IGAke3RhZ30gwrcgJHtiYXNlfeKGkiR7cGVha31MYCA6IGAke3RhZ30gwrcgZnJvbSAke2Jhc2V9TGA7CiAgICByZXR1cm4geyBtb2RlLCBzdGVwOiAwLCBhZGQ6IDAsIGJhc2UsIG1heCwgc2NhbGVScywgY3BsLCB0aWVyczogMCwgcGVhaywgY2FwcGVkOiBmYWxzZSwgbXVsdDogYmFzZSA+IDAgPyBwZWFrIC8gYmFzZSA6IDEsIHRhZywgbGFiZWwgfTsKICB9CiAgY29uc3QgdGllcnMgPSBkYXRlRnJvbSAmJiBkYXRlVG8gPyBNYXRoLmZsb29yKG1vbnRoc0VsYXBzZWQoZGF0ZUZyb20sIGRhdGVUbykgLyBwLnN0ZXApIDogMDsKICBjb25zdCBsYWRkZXIgPSBiYXNlICE9IG51bGwgPyBjYXBMb3RzKGJhc2UgKyB0aWVycyAqIHAuYWRkKSA6IG51bGw7CiAgY29uc3QgcGVhayA9IGFjdHVhbFBlYWsgPz8gbGFkZGVyOwogIGNvbnN0IGNhcHBlZCA9IGJhc2UgIT0gbnVsbCAmJiBtYXggPiAwICYmIGJhc2UgKyB0aWVycyAqIHAuYWRkID4gbWF4OwogIGNvbnN0IG11bHQgPSBiYXNlICE9IG51bGwgJiYgYmFzZSA+IDAgJiYgcGVhayAhPSBudWxsID8gcGVhayAvIGJhc2UgOiAxOwogIGNvbnN0IHRhZyA9IGArJHtwLmFkZH1MIC8gJHtwLnN0ZXB9bW8ke21heCA/IGAg4omkJHttYXh9TGAgOiAiIn0ke3NjYWxlUnMgPyAiIiA6ICIgwrcg4oK5IGZpeGVkIn1gOwogIGNvbnN0IGxhYmVsID0gcGVhayAhPSBudWxsICYmICh0aWVycyA+IDAgfHwgYWN0dWFsUGVhayAhPSBudWxsKSA/IGAke3RhZ30gwrcgJHtiYXNlfeKGkiR7cGVha31MJHtjYXBwZWQgPyAiIChjYXApIiA6ICIifWAgOiAoYmFzZSAhPSBudWxsID8gYCR7dGFnfSDCtyBmcm9tICR7YmFzZX1MYCA6IHRhZyk7CiAgcmV0dXJuIHsgbW9kZSwgLi4ucCwgYmFzZSwgbWF4LCBzY2FsZVJzLCBjcGw6IDAsIHRpZXJzLCBwZWFrLCBjYXBwZWQsIG11bHQsIHRhZywgbGFiZWwgfTsKfQoK", "lco_new": "ZXhwb3J0IGZ1bmN0aW9uIGxvdENvbXBPZihjZmcsIGRhdGVGcm9tLCBkYXRlVG8sIHN1bW1hcnkpIHsKICBjb25zdCBiYXNlID0gYmFzZUxvdHNPZihjZmcpOwogIGNvbnN0IG1vZGUgPSBsb3RDb21wTW9kZShjZmcpOwogIGNvbnN0IGNwbCA9IE51bWJlcihjZmc/LmxvdF9jb21wX2NhcGl0YWxfcGVyX2xvdCkgfHwgMDsKICBjb25zdCBwID0gbG90Q29tcFBhcnNlKGNmZyk7CiAgaWYgKG1vZGUgPT09ICJlcXVpdHkiID8gIShiYXNlID4gMCAmJiBjcGwgPiAwKSA6ICFwKSByZXR1cm4gbnVsbDsKICBjb25zdCByYXdNYXggPSBNYXRoLmZsb29yKE51bWJlcihjZmc/LmxvdF9jb21wX21heF9sb3RzKSkgfHwgMDsKICBjb25zdCBtYXggPSBiYXNlICE9IG51bGwgJiYgcmF3TWF4ID49IGJhc2UgPyByYXdNYXggOiAwOwogIGNvbnN0IHNjYWxlUnMgPSAhKGNmZz8ubG90X2NvbXBfc2NhbGVfcnMgPT09IGZhbHNlIHx8IFN0cmluZyhjZmc/LmxvdF9jb21wX3NjYWxlX3JzKS50b0xvd2VyQ2FzZSgpID09PSAiZmFsc2UiKTsKICAvLyDilIDilIAgTE9UX0NPTVBfRERfMjAyNjA5MjQg4pSA4pSAIGRyYXdkb3duIGd1YXJkOiAlIG9mIGVxdWl0eSBwZWFrOyBuZWVkcyBjYXBpdGFsIHBlciBsb3QKICBjb25zdCBkZFJhdyA9IE51bWJlcihjZmc/LmxvdF9jb21wX2RkX2xpbWl0X3BjdCkgfHwgMDsKICBjb25zdCBkZExpbWl0ID0gZGRSYXcgPiAwICYmIGRkUmF3IDwgMTAwICYmIGNwbCA+IDAgPyBkZFJhdyA6IDA7CiAgY29uc3QgZGRUYWcgPSBkZExpbWl0ID8gYCDCtyBEROKJpCR7U3RyaW5nKCtkZExpbWl0LnRvRml4ZWQoMikpfSXihpJiYXNlYCA6ICIiOwogIGNvbnN0IGNhcExvdHMgPSAobikgPT4gKG1heCA/IE1hdGgubWluKG4sIG1heCkgOiBuKTsKICAvLyBhY3R1YWwgcGVhayBmcm9tIHRoZSBwZXJzaXN0ZWQgcnVuLCB3aGVuIHdlIGhhdmUgaXQKICBjb25zdCBscyA9IGxvdFNpemVPZihjZmcsIHVuZGVmaW5lZCwgY2ZnPy51bmRlcmx5aW5nKTsKICBjb25zdCBhY3R1YWxQZWFrID0gc3VtbWFyeSAmJiBOdW1iZXIoc3VtbWFyeS5xdHlfbWF4KSA+IDAgJiYgbHMgPyBNYXRoLnJvdW5kKE51bWJlcihzdW1tYXJ5LnF0eV9tYXgpIC8gbHMpIDogbnVsbDsKICBpZiAobW9kZSA9PT0gImVxdWl0eSIpIHsKICAgIGNvbnN0IHBlYWsgPSBhY3R1YWxQZWFrID8/IGJhc2U7CiAgICBjb25zdCB0YWcgPSBgRXF1aXR5IOKCuSR7Zm10TChjcGwpfUwvbG90JHttYXggPyBgIOKJpCR7bWF4fUxgIDogIiJ9JHtzY2FsZVJzID8gIiIgOiAiIMK3IOKCuSBmaXhlZCJ9JHtkZFRhZ31gOwogICAgY29uc3QgbGFiZWwgPSBhY3R1YWxQZWFrICE9IG51bGwgPyBgJHt0YWd9IMK3ICR7YmFzZX3ihpIke3BlYWt9TGAgOiBgJHt0YWd9IMK3IGZyb20gJHtiYXNlfUxgOwogICAgcmV0dXJuIHsgbW9kZSwgc3RlcDogMCwgYWRkOiAwLCBiYXNlLCBtYXgsIHNjYWxlUnMsIGNwbCwgZGRMaW1pdCwgdGllcnM6IDAsIHBlYWssIGNhcHBlZDogZmFsc2UsIG11bHQ6IGJhc2UgPiAwID8gcGVhayAvIGJhc2UgOiAxLCB0YWcsIGxhYmVsIH07CiAgfQogIGNvbnN0IHRpZXJzID0gZGF0ZUZyb20gJiYgZGF0ZVRvID8gTWF0aC5mbG9vcihtb250aHNFbGFwc2VkKGRhdGVGcm9tLCBkYXRlVG8pIC8gcC5zdGVwKSA6IDA7CiAgY29uc3QgbGFkZGVyID0gYmFzZSAhPSBudWxsID8gY2FwTG90cyhiYXNlICsgdGllcnMgKiBwLmFkZCkgOiBudWxsOwogIGNvbnN0IHBlYWsgPSBhY3R1YWxQZWFrID8/IGxhZGRlcjsKICBjb25zdCBjYXBwZWQgPSBiYXNlICE9IG51bGwgJiYgbWF4ID4gMCAmJiBiYXNlICsgdGllcnMgKiBwLmFkZCA+IG1heDsKICBjb25zdCBtdWx0ID0gYmFzZSAhPSBudWxsICYmIGJhc2UgPiAwICYmIHBlYWsgIT0gbnVsbCA/IHBlYWsgLyBiYXNlIDogMTsKICBjb25zdCB0YWcgPSBgKyR7cC5hZGR9TCAvICR7cC5zdGVwfW1vJHttYXggPyBgIOKJpCR7bWF4fUxgIDogIiJ9JHtzY2FsZVJzID8gIiIgOiAiIMK3IOKCuSBmaXhlZCJ9JHtkZFRhZ31gOwogIGNvbnN0IGxhYmVsID0gcGVhayAhPSBudWxsICYmICh0aWVycyA+IDAgfHwgYWN0dWFsUGVhayAhPSBudWxsKSA/IGAke3RhZ30gwrcgJHtiYXNlfeKGkiR7cGVha31MJHtjYXBwZWQgPyAiIChjYXApIiA6ICIifWAgOiAoYmFzZSAhPSBudWxsID8gYCR7dGFnfSDCtyBmcm9tICR7YmFzZX1MYCA6IHRhZyk7CiAgcmV0dXJuIHsgbW9kZSwgLi4ucCwgYmFzZSwgbWF4LCBzY2FsZVJzLCBjcGwsIGRkTGltaXQsIHRpZXJzLCBwZWFrLCBjYXBwZWQsIG11bHQsIHRhZywgbGFiZWwgfTsKfQoK", "sub_old": "ICAgICAgICAgIHsvKiDilIDilIAgTE9UX0NPTVBfMjAyNjA5MjQgLyBMT1RfQ09NUF9NQVhfMjAyNjA5MjQgLyBMT1RfQ09NUF9FUV8yMDI2MDkyNCDilIDilIAKICAgICAgICAgICAgICBMb3QgY29tcG91bmRpbmc6IG9uZSBzdWItc2VjdGlvbiBmb3IgRVZFUlkgc3RyYXRlZ3ksIGZ1bGwgd2lkdGgsCiAgICAgICAgICAgICAgYmVsb3cgdGhlIHN0cmF0ZWd5J3Mgb3duIHBhcmFtZXRlcnMgc28gaXQgaXMgbmV2ZXIgbWl4ZWQgaW50bwogICAgICAgICAgICAgIHRoZW0uIFR3byBtb2RlcyDigJQgY2FsZW5kYXIgc3RlcCAoYmxhbmsgc3RlcCBvciBsb3RzID0gb2ZmKSBhbmQKICAgICAgICAgICAgICBlcXVpdHktYmFzZWQgKGxvdHMgZm9sbG93IHJlYWxpc2VkIFAmTCDDtyBjYXBpdGFsIHBlciBsb3QpLiAqL30KICAgICAgICAgIDxkaXYgc3R5bGU9e3sgZ3JpZENvbHVtbjogIjEgLyAtMSIsIG1hcmdpblRvcDogOCwgcGFkZGluZ1RvcDogMTAsIGJvcmRlclRvcDogYDFweCBzb2xpZCAke2NvbG9ycy5ib3JkZXIuZGFya31gIH19PgogICAgICAgICAgICA8ZGl2IHN0eWxlPXt7IC4uLnRtYVNlY0xhYmVsLCBtYXJnaW5Ub3A6IDAgfX0+TG90IGNvbXBvdW5kaW5nIDxzcGFuIHN0eWxlPXt7IHRleHRUcmFuc2Zvcm06ICJub25lIiwgbGV0dGVyU3BhY2luZzogMCwgZm9udFdlaWdodDogNDAwIH19PsK3IGFsbCBzdHJhdGVnaWVzIMK3IHtjb21wTW9kZSA9PT0gImVxdWl0eSIgPyAiZXF1aXR5LWJhc2VkIHNpemluZyIgOiAiYmxhbmsgPSBvZmYifTwvc3Bhbj48L2Rpdj4KICAgICAgICAgICAgPGRpdiBzdHlsZT17dG1hU2VjUm93fT4KICAgICAgICAgICAgICA8RmllbGQgbGFiZWw9Ik1vZGUiPgogICAgICAgICAgICAgICAgPHNlbGVjdCBzdHlsZT17eyAuLi5pbnB1dFN0eWxlLCB3aWR0aDogMTUwIH19IHZhbHVlPXtjb21wTW9kZX0gb25DaGFuZ2U9eyhlKSA9PiBzZXRDb21wTW9kZShlLnRhcmdldC52YWx1ZSA9PT0gImVxdWl0eSIgPyAiZXF1aXR5IiA6ICJjYWxlbmRhciIpfQogICAgICAgICAgICAgICAgICB0aXRsZT0iQ2FsZW5kYXIgc3RlcDogYWRkIGxvdHMgZXZlcnkgTiBtb250aHMuIEVxdWl0eS1iYXNlZDogbG90cyA9IGZsb29yKGVxdWl0eSDDtyBjYXBpdGFsIHBlciBsb3QpLCB3aGVyZSBlcXVpdHkgPSBiYXNlIGxvdHMgw5cgY2FwaXRhbCBwZXIgbG90ICsgcmVhbGlzZWQgbmV0IHNvIGZhci4iPgogICAgICAgICAgICAgICAgICA8b3B0aW9uIHZhbHVlPSJjYWxlbmRhciI+Q2FsZW5kYXIgc3RlcDwvb3B0aW9uPgogICAgICAgICAgICAgICAgICA8b3B0aW9uIHZhbHVlPSJlcXVpdHkiPkVxdWl0eS1iYXNlZDwvb3B0aW9uPgogICAgICAgICAgICAgICAgPC9zZWxlY3Q+CiAgICAgICAgICAgICAgPC9GaWVsZD4KICAgICAgICAgICAgICB7Y29tcE1vZGUgPT09ICJlcXVpdHkiID8gKAogICAgICAgICAgICAgICAgPEZpZWxkIGxhYmVsPSJDYXBpdGFsIHBlciBsb3QgKOKCuSkiPjxpbnB1dCB0eXBlPSJudW1iZXIiIG1pbj0iMCIgc3RlcD0iMTAwMCIgcGxhY2Vob2xkZXI9ImUuZy4gMTUwMDAwIiBzdHlsZT17eyAuLi5pbnB1dFN0eWxlLCB3aWR0aDogMTIwIH19IHZhbHVlPXtjb21wQ3BsfSBvbkNoYW5nZT17KGUpID0+IHNldENvbXBDcGwoZS50YXJnZXQudmFsdWUpfSB0aXRsZT0iUnVwZWVzIG9mIGNhcGl0YWwgdGhhdCBmdW5kIE9ORSBsb3QuIFN0YXJ0aW5nIGVxdWl0eSA9IGJhc2UgbG90cyDDlyB0aGlzOyBsb3RzIGFyZSByZWNvbXB1dGVkIGVhY2ggZGF5IGZyb20gcmVhbGlzZWQgbmV0ICh0cmFkZXMgY2xvc2VkIGJlZm9yZSB0aGF0IGRheSksIG1pbiAxIGxvdC4gQmxhbmsgPSBvZmYuIiAvPjwvRmllbGQ+CiAgICAgICAgICAgICAgKSA6ICgKICAgICAgICAgICAgICAgIDw+CiAgICAgICAgICAgICAgICAgIDxGaWVsZCBsYWJlbD0iU3RlcCAobW9udGhzKSI+PGlucHV0IHR5cGU9Im51bWJlciIgbWluPSIwIiBzdGVwPSIxIiBwbGFjZWhvbGRlcj0ib2ZmIiBzdHlsZT17eyAuLi5pbnB1dFN0eWxlLCB3aWR0aDogOTAgfX0gdmFsdWU9e2NvbXBTdGVwfSBvbkNoYW5nZT17KGUpID0+IHNldENvbXBTdGVwKGUudGFyZ2V0LnZhbHVlKX0gdGl0bGU9IkFkZCBsb3RzIGV2ZXJ5IE4gY2FsZW5kYXIgbW9udGhzIGZyb20gRGF0ZSBmcm9tIChhbm5pdmVyc2FyeS1iYXNlZCkuIEJsYW5rID0gb2ZmLiIgLz48L0ZpZWxkPgogICAgICAgICAgICAgICAgICA8RmllbGQgbGFiZWw9IkxvdHMgcGVyIHN0ZXAiPjxpbnB1dCB0eXBlPSJudW1iZXIiIG1pbj0iMCIgc3RlcD0iMSIgcGxhY2Vob2xkZXI9Im9mZiIgc3R5bGU9e3sgLi4uaW5wdXRTdHlsZSwgd2lkdGg6IDkwIH19IHZhbHVlPXtjb21wQWRkfSBvbkNoYW5nZT17KGUpID0+IHNldENvbXBBZGQoZS50YXJnZXQudmFsdWUpfSB0aXRsZT0iTG90cyBhZGRlZCBhdCBlYWNoIHN0ZXAuIEV2ZXJ5IGxlZyBzY2FsZXMgYnkgdGhlIHNhbWUgcmF0aW8sIHJvdW5kZWQsIG1pbiAxLiIgLz48L0ZpZWxkPgogICAgICAgICAgICAgICAgPC8+CiAgICAgICAgICAgICAgKX0KICAgICAgICAgICAgICA8RmllbGQgbGFiZWw9Ik1heCBsb3RzIj48aW5wdXQgdHlwZT0ibnVtYmVyIiBtaW49IjAiIHN0ZXA9IjEiIHBsYWNlaG9sZGVyPSJubyBjYXAiIHN0eWxlPXt7IC4uLmlucHV0U3R5bGUsIHdpZHRoOiA5MCB9fSB2YWx1ZT17Y29tcE1heH0gb25DaGFuZ2U9eyhlKSA9PiBzZXRDb21wTWF4KGUudGFyZ2V0LnZhbHVlKX0gdGl0bGU9IkxhZGRlciBjYXAg4oCUIHRoZSBtb3N0IGxvdHMgdGhlIHJ1biB3aWxsIGV2ZXIgdHJhZGUgKG1heGltdW0gcmlzaykuIEJsYW5rID0gbm8gY2FwOyBhIGNhcCBiZWxvdyB0aGUgYmFzZSBsb3RzIGlzIGlnbm9yZWQuIiAvPjwvRmllbGQ+CiAgICAgICAgICAgICAgPEZpZWxkIGxhYmVsPSLigrkga25vYnMiPgogICAgICAgICAgICAgICAgPHNlbGVjdCBzdHlsZT17eyAuLi5pbnB1dFN0eWxlLCB3aWR0aDogMTUwIH19IHZhbHVlPXtjb21wU2NhbGVScyA/ICJzY2FsZSIgOiAiZml4ZWQifSBvbkNoYW5nZT17KGUpID0+IHNldENvbXBTY2FsZVJzKGUudGFyZ2V0LnZhbHVlICE9PSAiZml4ZWQiKX0KICAgICAgICAgICAgICAgICAgdGl0bGU9IlNjYWxlIHdpdGggbG90czogTVRNIFNML3RhcmdldC90cmFpbCwg4oK5IGxvc3MgY2FwcyBhbmQgbGltaXRzIGdyb3cgd2l0aCB0aGUgcmF0aW8gKHRoZSBzdHJhdGVneSBzaXplZCB1cCkuIEtlZXAgZml4ZWQ6IHNhbWUg4oK5IHJpc2sgYnVkZ2V0IHdoaWxlIGxvdHMgZ3Jvdy4iPgogICAgICAgICAgICAgICAgICA8b3B0aW9uIHZhbHVlPSJzY2FsZSI+U2NhbGUgd2l0aCBsb3RzPC9vcHRpb24+CiAgICAgICAgICAgICAgICAgIDxvcHRpb24gdmFsdWU9ImZpeGVkIj5LZWVwIGZpeGVkIOKCuTwvb3B0aW9uPgogICAgICAgICAgICAgICAgPC9zZWxlY3Q+CiAgICAgICAgICAgICAgPC9GaWVsZD4KICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgIDxkaXYgc3R5bGU9e3sgZm9udFNpemU6IDExLCBjb2xvcjogY29sb3JzLnRleHQudGVydGlhcnksIGxpbmVIZWlnaHQ6IDEuNTUgfX0+CiAgICAgICAgICAgICAge2NvbXBQcmV2aWV3CiAgICAgICAgICAgICAgICA/IChjb21wUHJldmlldy5tb2RlID09PSAiZXF1aXR5IgogICAgICAgICAgICAgICAgICA/IDw+RXF1aXR5IHNpemluZzogc3RhcnQgPGI+e2NvbXBQcmV2aWV3LmJhc2UgPz8gIj8ifSBsb3RzPC9iPiBhdCDigrl7Zm10TChjb21wUHJldmlldy5jcGwpfUwgcGVyIGxvdCAo4oK5e2ZtdEwoKGNvbXBQcmV2aWV3LmJhc2UgfHwgMCkgKiBjb21wUHJldmlldy5jcGwpfUwpOyBlYWNoIGRheSBsb3RzID0g4oyKZXF1aXR5IMO3IGNhcGl0YWwgcGVyIGxvdOKMiywgbWluIDF7Y29tcFByZXZpZXcubWF4ID8gYCwgbWF4ICR7Y29tcFByZXZpZXcubWF4fWAgOiAiIn07IGVxdWl0eSBjb3VudHMgdHJhZGVzIGNsb3NlZCBiZWZvcmUgdGhhdCBkYXkgKG9wZW4gcG9zaXRpb25zIGV4Y2x1ZGVkKTsgbmV3IGVudHJpZXMgb25seTsge2NvbXBQcmV2aWV3LnNjYWxlUnMgPyAi4oK5IGtub2JzIHNjYWxlIHdpdGggdGhlIHJhdGlvIiA6ICLigrkga25vYnMgc3RheSBmaXhlZCJ9OyBydW5zIHNlcmlhbGx5IChwYXJhbGxlbCB3b3JrZXJzIGlnbm9yZWQpLjwvPgogICAgICAgICAgICAgICAgICA6IDw+TGFkZGVyOiA8Yj57Y29tcFByZXZpZXcuYmFzZSA/PyAiPyJ9IOKGkiB7Y29tcFByZXZpZXcucGVhayA/PyAiPyJ9IGxvdHM8L2I+IG92ZXIgdGhpcyBkYXRlIHJhbmdlICh7Y29tcFByZXZpZXcudGllcnN9IHN0ZXB7Y29tcFByZXZpZXcudGllcnMgPT09IDEgPyAiIiA6ICJzIn17Y29tcFByZXZpZXcuY2FwcGVkID8gYCwgY2FwcGVkIGF0ICR7Y29tcFByZXZpZXcubWF4fWAgOiAiIn0pOyBuZXcgZW50cmllcyBvbmx5IOKAlCBvcGVuIHBvc2l0aW9ucyBrZWVwIHRoZWlyIGVudHJ5IGxvdHM7IHtjb21wUHJldmlldy5zY2FsZVJzID8gIuKCuSBrbm9icyBzY2FsZSB3aXRoIHRoZSByYXRpbyIgOiAi4oK5IGtub2JzIHN0YXkgZml4ZWQifS48Lz4pCiAgICAgICAgICAgICAgICA6IDw+T2ZmIOKAlCBmbGF0IGxvdHMgZm9yIHRoZSB3aG9sZSBydW4uIFNldCBhIHN0ZXAgYW5kIGxvdHMgcGVyIHN0ZXAgKGUuZy4gMyBtb250aHMsICsxIGxvdCksIG9yIHN3aXRjaCB0byBlcXVpdHktYmFzZWQgc2l6aW5nLjwvPn0KICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICA8L2Rpdj4K", "sub_new": "ICAgICAgICAgIHsvKiDilIDilIAgTE9UX0NPTVBfMjAyNjA5MjQgLyBMT1RfQ09NUF9NQVhfMjAyNjA5MjQgLyBMT1RfQ09NUF9FUV8yMDI2MDkyNCDilIDilIAKICAgICAgICAgICAgICBMb3QgY29tcG91bmRpbmc6IG9uZSBzdWItc2VjdGlvbiBmb3IgRVZFUlkgc3RyYXRlZ3ksIGZ1bGwgd2lkdGgsCiAgICAgICAgICAgICAgYmVsb3cgdGhlIHN0cmF0ZWd5J3Mgb3duIHBhcmFtZXRlcnMgc28gaXQgaXMgbmV2ZXIgbWl4ZWQgaW50bwogICAgICAgICAgICAgIHRoZW0uIFR3byBtb2RlcyDigJQgY2FsZW5kYXIgc3RlcCAoYmxhbmsgc3RlcCBvciBsb3RzID0gb2ZmKSBhbmQKICAgICAgICAgICAgICBlcXVpdHktYmFzZWQgKGxvdHMgZm9sbG93IHJlYWxpc2VkIFAmTCDDtyBjYXBpdGFsIHBlciBsb3QpLiAqL30KICAgICAgICAgIDxkaXYgc3R5bGU9e3sgZ3JpZENvbHVtbjogIjEgLyAtMSIsIG1hcmdpblRvcDogOCwgcGFkZGluZ1RvcDogMTAsIGJvcmRlclRvcDogYDFweCBzb2xpZCAke2NvbG9ycy5ib3JkZXIuZGFya31gIH19PgogICAgICAgICAgICA8ZGl2IHN0eWxlPXt7IC4uLnRtYVNlY0xhYmVsLCBtYXJnaW5Ub3A6IDAgfX0+TG90IGNvbXBvdW5kaW5nIDxzcGFuIHN0eWxlPXt7IHRleHRUcmFuc2Zvcm06ICJub25lIiwgbGV0dGVyU3BhY2luZzogMCwgZm9udFdlaWdodDogNDAwIH19PsK3IGFsbCBzdHJhdGVnaWVzIMK3IHtjb21wTW9kZSA9PT0gImVxdWl0eSIgPyAiZXF1aXR5LWJhc2VkIHNpemluZyIgOiAiYmxhbmsgPSBvZmYifTwvc3Bhbj48L2Rpdj4KICAgICAgICAgICAgPGRpdiBzdHlsZT17dG1hU2VjUm93fT4KICAgICAgICAgICAgICA8RmllbGQgbGFiZWw9Ik1vZGUiPgogICAgICAgICAgICAgICAgPHNlbGVjdCBzdHlsZT17eyAuLi5pbnB1dFN0eWxlLCB3aWR0aDogMTUwIH19IHZhbHVlPXtjb21wTW9kZX0gb25DaGFuZ2U9eyhlKSA9PiBzZXRDb21wTW9kZShlLnRhcmdldC52YWx1ZSA9PT0gImVxdWl0eSIgPyAiZXF1aXR5IiA6ICJjYWxlbmRhciIpfQogICAgICAgICAgICAgICAgICB0aXRsZT0iQ2FsZW5kYXIgc3RlcDogYWRkIGxvdHMgZXZlcnkgTiBtb250aHMuIEVxdWl0eS1iYXNlZDogbG90cyA9IGZsb29yKGVxdWl0eSDDtyBjYXBpdGFsIHBlciBsb3QpLCB3aGVyZSBlcXVpdHkgPSBiYXNlIGxvdHMgw5cgY2FwaXRhbCBwZXIgbG90ICsgcmVhbGlzZWQgbmV0IHNvIGZhci4iPgogICAgICAgICAgICAgICAgICA8b3B0aW9uIHZhbHVlPSJjYWxlbmRhciI+Q2FsZW5kYXIgc3RlcDwvb3B0aW9uPgogICAgICAgICAgICAgICAgICA8b3B0aW9uIHZhbHVlPSJlcXVpdHkiPkVxdWl0eS1iYXNlZDwvb3B0aW9uPgogICAgICAgICAgICAgICAgPC9zZWxlY3Q+CiAgICAgICAgICAgICAgPC9GaWVsZD4KICAgICAgICAgICAgICB7Y29tcE1vZGUgPT09ICJlcXVpdHkiID8gKAogICAgICAgICAgICAgICAgPEZpZWxkIGxhYmVsPSJDYXBpdGFsIHBlciBsb3QgKOKCuSkiPjxpbnB1dCB0eXBlPSJudW1iZXIiIG1pbj0iMCIgc3RlcD0iMTAwMCIgcGxhY2Vob2xkZXI9ImUuZy4gMTUwMDAwIiBzdHlsZT17eyAuLi5pbnB1dFN0eWxlLCB3aWR0aDogMTIwIH19IHZhbHVlPXtjb21wQ3BsfSBvbkNoYW5nZT17KGUpID0+IHNldENvbXBDcGwoZS50YXJnZXQudmFsdWUpfSB0aXRsZT0iUnVwZWVzIG9mIGNhcGl0YWwgdGhhdCBmdW5kIE9ORSBsb3QuIFN0YXJ0aW5nIGVxdWl0eSA9IGJhc2UgbG90cyDDlyB0aGlzOyBsb3RzIGFyZSByZWNvbXB1dGVkIGVhY2ggZGF5IGZyb20gcmVhbGlzZWQgbmV0ICh0cmFkZXMgY2xvc2VkIGJlZm9yZSB0aGF0IGRheSksIG1pbiAxIGxvdC4gQmxhbmsgPSBvZmYuIiAvPjwvRmllbGQ+CiAgICAgICAgICAgICAgKSA6ICgKICAgICAgICAgICAgICAgIDw+CiAgICAgICAgICAgICAgICAgIDxGaWVsZCBsYWJlbD0iU3RlcCAobW9udGhzKSI+PGlucHV0IHR5cGU9Im51bWJlciIgbWluPSIwIiBzdGVwPSIxIiBwbGFjZWhvbGRlcj0ib2ZmIiBzdHlsZT17eyAuLi5pbnB1dFN0eWxlLCB3aWR0aDogOTAgfX0gdmFsdWU9e2NvbXBTdGVwfSBvbkNoYW5nZT17KGUpID0+IHNldENvbXBTdGVwKGUudGFyZ2V0LnZhbHVlKX0gdGl0bGU9IkFkZCBsb3RzIGV2ZXJ5IE4gY2FsZW5kYXIgbW9udGhzIGZyb20gRGF0ZSBmcm9tIChhbm5pdmVyc2FyeS1iYXNlZCkuIEJsYW5rID0gb2ZmLiIgLz48L0ZpZWxkPgogICAgICAgICAgICAgICAgICA8RmllbGQgbGFiZWw9IkxvdHMgcGVyIHN0ZXAiPjxpbnB1dCB0eXBlPSJudW1iZXIiIG1pbj0iMCIgc3RlcD0iMSIgcGxhY2Vob2xkZXI9Im9mZiIgc3R5bGU9e3sgLi4uaW5wdXRTdHlsZSwgd2lkdGg6IDkwIH19IHZhbHVlPXtjb21wQWRkfSBvbkNoYW5nZT17KGUpID0+IHNldENvbXBBZGQoZS50YXJnZXQudmFsdWUpfSB0aXRsZT0iTG90cyBhZGRlZCBhdCBlYWNoIHN0ZXAuIEV2ZXJ5IGxlZyBzY2FsZXMgYnkgdGhlIHNhbWUgcmF0aW8sIHJvdW5kZWQsIG1pbiAxLiIgLz48L0ZpZWxkPgogICAgICAgICAgICAgICAgPC8+CiAgICAgICAgICAgICAgKX0KICAgICAgICAgICAgICB7Lyog4pSA4pSAIExPVF9DT01QX0REXzIwMjYwOTI0IOKUgOKUgCBkcmF3ZG93biBndWFyZCAoYm90aCBtb2Rlcyk6IHdoZW4gZXF1aXR5IGZhbGxzCiAgICAgICAgICAgICAgICAgIHRoaXMgJSBiZWxvdyBpdHMgcGVhaywgbG90cyBkcm9wIHRvIEJBU0UgdW50aWwgYSBuZXcgZXF1aXR5IGhpZ2guCiAgICAgICAgICAgICAgICAgIENhbGVuZGFyIG1vZGUgbmVlZHMgY2FwaXRhbCBwZXIgbG90IHRvbyDigJQgaXQgaXMgdGhlIGd1YXJkJ3MgZGVub21pbmF0b3IuICovfQogICAgICAgICAgICAgIHtjb21wTW9kZSAhPT0gImVxdWl0eSIgJiYgTnVtYmVyKGNvbXBEZCkgPiAwICYmICgKICAgICAgICAgICAgICAgIDxGaWVsZCBsYWJlbD0iQ2FwaXRhbCBwZXIgbG90ICjigrkpIj48aW5wdXQgdHlwZT0ibnVtYmVyIiBtaW49IjAiIHN0ZXA9IjEwMDAiIHBsYWNlaG9sZGVyPSJmb3IgREQgJSIgc3R5bGU9e3sgLi4uaW5wdXRTdHlsZSwgd2lkdGg6IDEyMCB9fSB2YWx1ZT17Y29tcENwbH0gb25DaGFuZ2U9eyhlKSA9PiBzZXRDb21wQ3BsKGUudGFyZ2V0LnZhbHVlKX0gdGl0bGU9Ik9ubHkgdXNlZCBieSB0aGUgREQgZ3VhcmQgaW4gY2FsZW5kYXIgbW9kZTogZXF1aXR5ID0gYmFzZSBsb3RzIMOXIHRoaXMgKyByZWFsaXNlZCBuZXQuIiAvPjwvRmllbGQ+CiAgICAgICAgICAgICAgKX0KICAgICAgICAgICAgICA8RmllbGQgbGFiZWw9Ik1heCBERCAoJSBvZiBlcXVpdHkpIj48aW5wdXQgdHlwZT0ibnVtYmVyIiBtaW49IjAiIG1heD0iOTkiIHN0ZXA9IjEiIHBsYWNlaG9sZGVyPSJvZmYiIHN0eWxlPXt7IC4uLmlucHV0U3R5bGUsIHdpZHRoOiA5MCB9fSB2YWx1ZT17Y29tcERkfSBvbkNoYW5nZT17KGUpID0+IHNldENvbXBEZChlLnRhcmdldC52YWx1ZSl9IHRpdGxlPSJEcmF3ZG93biBndWFyZC4gV2hlbiBlcXVpdHkgKGJhc2UgbG90cyDDlyBjYXBpdGFsIHBlciBsb3QgKyByZWFsaXNlZCBuZXQpIGlzIHRoaXMgJSBiZWxvdyBpdHMgcGVhaywgbG90cyBkcm9wIHRvIGJhc2UgdW50aWwgZXF1aXR5IG1ha2VzIGEgbmV3IGhpZ2guIEJsYW5rID0gb2ZmLiIgLz48L0ZpZWxkPgogICAgICAgICAgICAgIDxGaWVsZCBsYWJlbD0iTWF4IGxvdHMiPjxpbnB1dCB0eXBlPSJudW1iZXIiIG1pbj0iMCIgc3RlcD0iMSIgcGxhY2Vob2xkZXI9Im5vIGNhcCIgc3R5bGU9e3sgLi4uaW5wdXRTdHlsZSwgd2lkdGg6IDkwIH19IHZhbHVlPXtjb21wTWF4fSBvbkNoYW5nZT17KGUpID0+IHNldENvbXBNYXgoZS50YXJnZXQudmFsdWUpfSB0aXRsZT0iTGFkZGVyIGNhcCDigJQgdGhlIG1vc3QgbG90cyB0aGUgcnVuIHdpbGwgZXZlciB0cmFkZSAobWF4aW11bSByaXNrKS4gQmxhbmsgPSBubyBjYXA7IGEgY2FwIGJlbG93IHRoZSBiYXNlIGxvdHMgaXMgaWdub3JlZC4iIC8+PC9GaWVsZD4KICAgICAgICAgICAgICA8RmllbGQgbGFiZWw9IuKCuSBrbm9icyI+CiAgICAgICAgICAgICAgICA8c2VsZWN0IHN0eWxlPXt7IC4uLmlucHV0U3R5bGUsIHdpZHRoOiAxNTAgfX0gdmFsdWU9e2NvbXBTY2FsZVJzID8gInNjYWxlIiA6ICJmaXhlZCJ9IG9uQ2hhbmdlPXsoZSkgPT4gc2V0Q29tcFNjYWxlUnMoZS50YXJnZXQudmFsdWUgIT09ICJmaXhlZCIpfQogICAgICAgICAgICAgICAgICB0aXRsZT0iU2NhbGUgd2l0aCBsb3RzOiBNVE0gU0wvdGFyZ2V0L3RyYWlsLCDigrkgbG9zcyBjYXBzIGFuZCBsaW1pdHMgZ3JvdyB3aXRoIHRoZSByYXRpbyAodGhlIHN0cmF0ZWd5IHNpemVkIHVwKS4gS2VlcCBmaXhlZDogc2FtZSDigrkgcmlzayBidWRnZXQgd2hpbGUgbG90cyBncm93LiI+CiAgICAgICAgICAgICAgICAgIDxvcHRpb24gdmFsdWU9InNjYWxlIj5TY2FsZSB3aXRoIGxvdHM8L29wdGlvbj4KICAgICAgICAgICAgICAgICAgPG9wdGlvbiB2YWx1ZT0iZml4ZWQiPktlZXAgZml4ZWQg4oK5PC9vcHRpb24+CiAgICAgICAgICAgICAgICA8L3NlbGVjdD4KICAgICAgICAgICAgICA8L0ZpZWxkPgogICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgPGRpdiBzdHlsZT17eyBmb250U2l6ZTogMTEsIGNvbG9yOiBjb2xvcnMudGV4dC50ZXJ0aWFyeSwgbGluZUhlaWdodDogMS41NSB9fT4KICAgICAgICAgICAgICB7Y29tcFByZXZpZXcKICAgICAgICAgICAgICAgID8gKGNvbXBQcmV2aWV3Lm1vZGUgPT09ICJlcXVpdHkiCiAgICAgICAgICAgICAgICAgID8gPD5FcXVpdHkgc2l6aW5nOiBzdGFydCA8Yj57Y29tcFByZXZpZXcuYmFzZSA/PyAiPyJ9IGxvdHM8L2I+IGF0IOKCuXtmbXRMKGNvbXBQcmV2aWV3LmNwbCl9TCBwZXIgbG90ICjigrl7Zm10TCgoY29tcFByZXZpZXcuYmFzZSB8fCAwKSAqIGNvbXBQcmV2aWV3LmNwbCl9TCk7IGVhY2ggZGF5IGxvdHMgPSDijIplcXVpdHkgw7cgY2FwaXRhbCBwZXIgbG904oyLLCBtaW4gMXtjb21wUHJldmlldy5tYXggPyBgLCBtYXggJHtjb21wUHJldmlldy5tYXh9YCA6ICIifTsgZXF1aXR5IGNvdW50cyB0cmFkZXMgY2xvc2VkIGJlZm9yZSB0aGF0IGRheSAob3BlbiBwb3NpdGlvbnMgZXhjbHVkZWQpOyBuZXcgZW50cmllcyBvbmx5OyB7Y29tcFByZXZpZXcuc2NhbGVScyA/ICLigrkga25vYnMgc2NhbGUgd2l0aCB0aGUgcmF0aW8iIDogIuKCuSBrbm9icyBzdGF5IGZpeGVkIn17Y29tcFByZXZpZXcuZGRMaW1pdCA/IDw+OyA8Yj5ERCBndWFyZDwvYj46IGJlbG93IHtjb21wUHJldmlldy5kZExpbWl0fSUgb2YgZXF1aXR5IHBlYWsgbG90cyBkcm9wIHRvIGJhc2UgdW50aWwgYSBuZXcgaGlnaDwvPiA6IG51bGx9OyBydW5zIHNlcmlhbGx5IChwYXJhbGxlbCB3b3JrZXJzIGlnbm9yZWQpLjwvPgogICAgICAgICAgICAgICAgICA6IDw+TGFkZGVyOiA8Yj57Y29tcFByZXZpZXcuYmFzZSA/PyAiPyJ9IOKGkiB7Y29tcFByZXZpZXcucGVhayA/PyAiPyJ9IGxvdHM8L2I+IG92ZXIgdGhpcyBkYXRlIHJhbmdlICh7Y29tcFByZXZpZXcudGllcnN9IHN0ZXB7Y29tcFByZXZpZXcudGllcnMgPT09IDEgPyAiIiA6ICJzIn17Y29tcFByZXZpZXcuY2FwcGVkID8gYCwgY2FwcGVkIGF0ICR7Y29tcFByZXZpZXcubWF4fWAgOiAiIn0pOyBuZXcgZW50cmllcyBvbmx5IOKAlCBvcGVuIHBvc2l0aW9ucyBrZWVwIHRoZWlyIGVudHJ5IGxvdHM7IHtjb21wUHJldmlldy5zY2FsZVJzID8gIuKCuSBrbm9icyBzY2FsZSB3aXRoIHRoZSByYXRpbyIgOiAi4oK5IGtub2JzIHN0YXkgZml4ZWQifXtjb21wUHJldmlldy5kZExpbWl0ID8gPD47IDxiPkREIGd1YXJkPC9iPjogYmVsb3cge2NvbXBQcmV2aWV3LmRkTGltaXR9JSBvZiBlcXVpdHkgcGVhayAo4oK5e2ZtdEwoY29tcFByZXZpZXcuY3BsKX1ML2xvdCBiYXNpcykgbG90cyBkcm9wIHRvIGJhc2UgdW50aWwgYSBuZXcgaGlnaDwvPiA6IChOdW1iZXIoY29tcERkKSA+IDAgJiYgIWNvbXBQcmV2aWV3LmNwbCA/IDw+OyBERCBndWFyZCBuZWVkcyBjYXBpdGFsIHBlciBsb3Q8Lz4gOiBudWxsKX0uPC8+KQogICAgICAgICAgICAgICAgOiA8Pk9mZiDigJQgZmxhdCBsb3RzIGZvciB0aGUgd2hvbGUgcnVuLiBTZXQgYSBzdGVwIGFuZCBsb3RzIHBlciBzdGVwIChlLmcuIDMgbW9udGhzLCArMSBsb3QpLCBvciBzd2l0Y2ggdG8gZXF1aXR5LWJhc2VkIHNpemluZy48Lz59CiAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgPC9kaXY+Cg=="}


def frag(k):
    return base64.b64decode(FRAG_B64[k]).decode("utf-8")


EDITS = {}


def E(path, *ops):
    EDITS.setdefault(path, []).extend(ops)


# ═══════════════════════════ backend: shared module ═══════════════════════
E(f"{BACKEND}/engine/lot_compounding.py",
  ("replace", 'KEY_CPL = "lot_comp_capital_per_lot"       # ₹ that fund ONE lot (equity mode)\n',
   'KEY_CPL = "lot_comp_capital_per_lot"       # ₹ that fund ONE lot (equity mode)\n'
   "# ── LOT_COMP_DD_20260924 ── drawdown guard (both modes; needs capital per lot)\n"
   'KEY_DD = "lot_comp_dd_limit_pct"           # % of equity peak; 0 / absent / ≥100 = off\n'),
  ("replace", '                 "mode", "cpl", "_eq_lots", "_eq_day", "_eq_equity", "_eq_ladder")   # ── LOT_COMP_EQ_20260924 ──\n',
   '                 "mode", "cpl", "_eq_lots", "_eq_day", "_eq_equity", "_eq_ladder",   # ── LOT_COMP_EQ_20260924 ──\n'
   '                 "dd_limit", "dd_guard_on", "dd_peak", "dd_active", "_dd_events", "_dd_days")   # ── LOT_COMP_DD_20260924 ──\n'),
  ("replace", "        self._eq_ladder: List[tuple] = []   # (day, lots) at each change\n",
   "        self._eq_ladder: List[tuple] = []   # (day, lots) at each change\n"
   "        # ── LOT_COMP_DD_20260924 ── drawdown guard state\n"
   "        try:\n"
   "            _dd = float((cfg or {}).get(KEY_DD) or 0) if isinstance(cfg, dict) else 0.0\n"
   "        except (TypeError, ValueError):\n"
   "            _dd = 0.0\n"
   "        self.dd_limit = _dd / 100.0 if 0 < _dd < 100 else 0.0\n"
   "        self.dd_guard_on = bool(self.on and self.dd_limit > 0 and self.cpl > 0)\n"
   "        self.dd_peak = float(self.base) * self.cpl\n"
   "        self.dd_active = False\n"
   "        self._dd_events: List[dict] = []\n"
   "        self._dd_days = 0\n"),
  ("replace", "        if not self.on:\n            return self.base\n"
              '        if self.mode == "equity":   # ── LOT_COMP_EQ_20260924 ──\n'
              "            return self._eq_lots\n"
              "        n = self.base + self.tier(day) * self.add\n"
              "        return min(n, self.max_lots) if self.max_lots else n   # ── LOT_COMP_MAX_20260924 ──\n",
   "        if not self.on:\n            return self.base\n"
   '        if self.mode == "equity":   # ── LOT_COMP_EQ_20260924 ──\n'
   "            n = self._eq_lots\n"
   "        else:\n"
   "            n = self.base + self.tier(day) * self.add\n"
   "            if self.max_lots:   # ── LOT_COMP_MAX_20260924 ──\n"
   "                n = min(n, self.max_lots)\n"
   "        if self.dd_active:   # ── LOT_COMP_DD_20260924 ── hard drop: never above base while guarded\n"
   "            n = min(n, self.base)\n"
   "        return n\n"),
  ("replace", '        if not (self.on and self.mode == "equity"):\n            return self.lots(day)\n'
              "        d = _as_date(day)\n        if d is None or d == self._eq_day:\n            return self._eq_lots\n"
              "        net = 0.0\n        for t in (trades or ()):\n            v = _trade_net(t)\n            if v is not None:\n                net += v\n"
              "        self._eq_day = d\n        self._eq_equity = float(self.base) * self.cpl + net\n"
              "        n = self.equity_lots(net)\n        if n != self._eq_lots or not self._eq_ladder:\n            self._eq_ladder.append((d, n))\n        self._eq_lots = n\n        return n\n",
   '        if not self.on or (self.mode != "equity" and not self.dd_guard_on):   # ── LOT_COMP_DD_20260924 ── guard needs equity in calendar mode too\n'
   "            return self.lots(day)\n"
   "        d = _as_date(day)\n        if d is None or d == self._eq_day:\n            return self.lots(day)\n"
   "        net = 0.0\n        for t in (trades or ()):\n            v = _trade_net(t)\n            if v is not None:\n                net += v\n"
   "        self._eq_day = d\n        self._eq_equity = float(self.base) * self.cpl + net\n"
   "        # ── LOT_COMP_DD_20260924 ── guard: breach at ≥ limit below the peak, hard\n"
   "        # drop to base, released only by a NEW equity high\n"
   "        if self.dd_guard_on:\n"
   "            eqty = self._eq_equity\n"
   "            if eqty > self.dd_peak:\n"
   "                self.dd_peak = eqty\n"
   "                if self.dd_active:\n"
   "                    self.dd_active = False\n"
   '                    self._dd_events.append({"type": "recover", "day": d.isoformat(), "equity": eqty})\n'
   "            elif (not self.dd_active and self.dd_peak > 0\n"
   "                  and (self.dd_peak - eqty) / self.dd_peak >= self.dd_limit):\n"
   "                self.dd_active = True\n"
   '                self._dd_events.append({"type": "breach", "day": d.isoformat(), "equity": eqty,\n'
   '                                        "peak": self.dd_peak,\n'
   '                                        "dd_pct": round(100.0 * (self.dd_peak - eqty) / self.dd_peak, 2)})\n'
   "            if self.dd_active:\n"
   "                self._dd_days += 1\n"
   '        if self.mode == "equity":\n'
   "            self._eq_lots = self.equity_lots(net)\n"
   "        eff = self.lots(d)\n"
   "        if not self._eq_ladder or eff != self._eq_ladder[-1][1]:\n"
   "            self._eq_ladder.append((d, eff))\n"
   "        return eff\n"),
  ("replace", '                "ladder": [{"from": d.isoformat(), "lots": n} for d, n in self._eq_ladder],\n            }\n',
   '                "ladder": [{"from": d.isoformat(), "lots": n} for d, n in self._eq_ladder],\n'
   '                "dd_guard": self._dd_diag(),   # ── LOT_COMP_DD_20260924 ──\n'
   "            }\n"),
  ("replace", '                      for t, rng in sorted(self._seen.items())],\n        }\n',
   '                      for t, rng in sorted(self._seen.items())],\n'
   '            "dd_guard": self._dd_diag(),   # ── LOT_COMP_DD_20260924 ──\n'
   '            "ladder": [{"from": d.isoformat(), "lots": n} for d, n in self._eq_ladder],\n'
   "        }\n"
   "\n"
   "    def _dd_diag(self) -> dict:   # ── LOT_COMP_DD_20260924 ──\n"
   "        if not self.dd_guard_on:\n"
   '            return {"on": False}\n'
   '        return {"on": True, "limit_pct": round(self.dd_limit * 100.0, 4), "peak": self.dd_peak,\n'
   '                "active": self.dd_active, "days": self._dd_days, "events": list(self._dd_events)}\n'),
  ("replace", '            return (f"lot_comp equity cpl={self.cpl:.0f} base={self.base}"\n',
   '            return (f"lot_comp equity cpl={self.cpl:.0f} base={self.base}"\n'
   '                    f"{(\' dd=\' + format(self.dd_limit * 100, \'g\') + \'%\') if self.dd_guard_on else \'\'}"   # ── LOT_COMP_DD_20260924 ──\n'),
  ("replace", '                f"{(\' max=\' + str(self.max_lots)) if self.max_lots else \'\'}"\n                f"{\'\' if self.scale_rs_on else \' rs=fixed\'}")   # ── LOT_COMP_MAX_20260924 ──\n',
   '                f"{(\' max=\' + str(self.max_lots)) if self.max_lots else \'\'}"\n'
   '                f"{(\' dd=\' + format(self.dd_limit * 100, \'g\') + \'%\') if self.dd_guard_on else \'\'}"   # ── LOT_COMP_DD_20260924 ──\n'
   '                f"{\'\' if self.scale_rs_on else \' rs=fixed\'}")   # ── LOT_COMP_MAX_20260924 ──\n'))

# ═══════════════════════════ frontend ═════════════════════════════════════
E(f"{FRONTEND}/backtest/lotCompounding.js", ("replace", frag("lco_old"), frag("lco_new")))

E(f"{FRONTEND}/Backtest.jsx",
  ("replace", '  const [compCpl, setCompCpl] = useState(() => loadLotComp().cpl ?? "");   // ── LOT_COMP_EQ_20260924 ── capital per lot (₹)\n',
   '  const [compCpl, setCompCpl] = useState(() => loadLotComp().cpl ?? "");   // ── LOT_COMP_EQ_20260924 ── capital per lot (₹)\n'
   '  const [compDd, setCompDd] = useState(() => loadLotComp().dd ?? "");   // ── LOT_COMP_DD_20260924 ── max DD % of equity peak\n'),
  ("replace", "    try { localStorage.setItem(LOT_COMP_LS_KEY, JSON.stringify({ step: compStep, add: compAdd, max: compMax, scaleRs: compScaleRs, mode: compMode, cpl: compCpl })); } catch { /* ignore */ }\n"
              "  }, [compStep, compAdd, compMax, compScaleRs, compMode, compCpl]);\n",
   "    try { localStorage.setItem(LOT_COMP_LS_KEY, JSON.stringify({ step: compStep, add: compAdd, max: compMax, scaleRs: compScaleRs, mode: compMode, cpl: compCpl, dd: compDd })); } catch { /* ignore */ }\n"
   "  }, [compStep, compAdd, compMax, compScaleRs, compMode, compCpl, compDd]);\n"),
  ("replace", "    const extras = { ...(max > 0 ? { lot_comp_max_lots: max } : {}), ...(compScaleRs ? {} : { lot_comp_scale_rs: false }) };\n"
              "    // ── LOT_COMP_EQ_20260924 ── equity mode: mode + capital per lot, no step/add\n"
              '    if (compMode === "equity") {\n'
              "      const cpl = Math.floor(Number(compCpl)) || 0;\n"
              "      if (!base || cpl <= 0) return base;\n"
              '      return { ...base, lot_comp_mode: "equity", lot_comp_capital_per_lot: cpl, ...extras };\n'
              "    }\n"
              "    if (!base || step <= 0 || add <= 0) return base;\n"
              "    return { ...base, lot_comp_step_months: step, lot_comp_add_lots: add, ...extras };\n"
              "  }, [buildConfigBase, compStep, compAdd, compMax, compScaleRs, compMode, compCpl]);\n",
   "    // ── LOT_COMP_DD_20260924 ── DD guard emitted only when set (0 < % < 100);\n"
   "    // in calendar mode it also needs capital per lot (its denominator).\n"
   "    const dd = Number(compDd) || 0;\n"
   "    const cpl = Math.floor(Number(compCpl)) || 0;\n"
   "    const ddExtra = dd > 0 && dd < 100 ? { lot_comp_dd_limit_pct: dd } : {};\n"
   "    const extras = { ...(max > 0 ? { lot_comp_max_lots: max } : {}), ...(compScaleRs ? {} : { lot_comp_scale_rs: false }), ...ddExtra };\n"
   "    // ── LOT_COMP_EQ_20260924 ── equity mode: mode + capital per lot, no step/add\n"
   '    if (compMode === "equity") {\n'
   "      if (!base || cpl <= 0) return base;\n"
   '      return { ...base, lot_comp_mode: "equity", lot_comp_capital_per_lot: cpl, ...extras };\n'
   "    }\n"
   "    if (!base || step <= 0 || add <= 0) return base;\n"
   "    return { ...base, lot_comp_step_months: step, lot_comp_add_lots: add, ...extras,\n"
   "      ...(dd > 0 && dd < 100 && cpl > 0 ? { lot_comp_capital_per_lot: cpl } : {}) };\n"
   "  }, [buildConfigBase, compStep, compAdd, compMax, compScaleRs, compMode, compCpl, compDd]);\n"),
  ("replace", frag("sub_old"), frag("sub_new")))

E(f"{FRONTEND}/backtest/SweepBuilder.jsx",
  ("replace", '    fmt: (v) => (v > 0 ? `₹${String(+(v / 100000).toFixed(2))}L/lot` : "cplOFF") },\n',
   '    fmt: (v) => (v > 0 ? `₹${String(+(v / 100000).toFixed(2))}L/lot` : "cplOFF") },\n'
   "  // ── LOT_COMP_DD_20260924 ── drawdown guard (% of equity peak; 0 = off)\n"
   '  { key: "lot_comp_dd", label: "Compound max DD %", strategies: LOT_COMP_STRATS,\n'
   '    hint: "0, 8, 12", parse: _num,\n'
   "    apply: (c, v) => { if (v > 0 && v < 100) c.lot_comp_dd_limit_pct = v; else delete c.lot_comp_dd_limit_pct; },\n"
   '    fmt: (v) => (v > 0 && v < 100 ? `DD≤${v}%` : "ddOFF") },\n'))


# ═══════════════════════════ machinery ═══════════════════════════════════

def die(msg):
    print(f"\nABORT: {msg}")
    sys.exit(1)


def read(rel):
    with open(os.path.join(ROOT, rel), encoding="utf-8") as f:
        return f.read()


def apply_ops(text, ops, rel):
    for kind, old, new in ops:
        if kind == "replace":
            n = text.count(old)
            if n != 1:
                die(f"{rel}: anchor found {n}× (need 1): {old.splitlines()[0][:90]!r}")
            text = text.replace(old, new)
        else:
            die(f"bad op kind {kind}")
    return text


def git_dirty(rels):
    try:
        out = subprocess.run(["git", "status", "--porcelain", "--"] + rels, cwd=ROOT,
                             capture_output=True, text=True, timeout=30).stdout
    except Exception:
        return []
    return [l for l in out.splitlines() if l.strip() and not l.startswith("??")]


def main():
    print(f"── {FENCE} ── root {ROOT}")
    if not os.path.isdir(os.path.join(ROOT, BACKEND)) or not os.path.isdir(os.path.join(ROOT, FRONTEND)):
        die("run from the scalp-app repo root (backend/ and frontend/ not found)")
    targets = list(EDITS.keys())
    for rel in targets:
        if not os.path.exists(os.path.join(ROOT, rel)):
            die(f"missing target {rel}")
        if FENCE in read(rel):
            die(f"{FENCE} already present in {rel} — nothing to do")
    for rel in PAYLOADS_B64:
        if os.path.exists(os.path.join(ROOT, rel)):
            die(f"{rel} already exists — mixed state; remove it and re-run ONLY this script")
    for rel, fence in PREREQ.items():
        if fence not in read(rel):
            die(f"prerequisite {fence} not found in {rel} — apply the lot_compounding → max → equity chain first")
    print(f"   prerequisites ok ({len(PREREQ)})")
    dirty = git_dirty(targets)
    if dirty:
        print("   git status shows uncommitted changes on targets:")
        for l in dirty:
            print("     ", l)
        if not ALLOW_DIRTY:
            die("an `M` on a target is a stop sign; if that M is the parent chain not yet committed, re-run with --allow-dirty")
        print("   --allow-dirty: continuing")

    staged = {rel: apply_ops(read(rel), ops, rel) for rel, ops in EDITS.items()}
    for rel, b64 in PAYLOADS_B64.items():
        staged[rel] = base64.b64decode(b64).decode("utf-8")
    tmp = tempfile.mkdtemp(prefix="lot_comp_dd_gate_")
    for rel, txt in staged.items():
        if rel.endswith(".py"):
            p = os.path.join(tmp, os.path.basename(rel))
            with open(p, "w", encoding="utf-8") as f:
                f.write(txt)
            try:
                py_compile.compile(p, doraise=True)
            except py_compile.PyCompileError as e:
                die(f"py_compile failed for {rel}: {e}")
    shutil.rmtree(tmp, ignore_errors=True)
    print(f"   {len(EDITS)} files edited in memory, {len(PAYLOADS_B64)} payload; py_compile gate ok")

    written = []
    for rel, txt in staged.items():
        abs_ = os.path.join(ROOT, rel)
        if os.path.exists(abs_):
            shutil.copy2(abs_, abs_ + f".bak-{FENCE}")
        os.makedirs(os.path.dirname(abs_), exist_ok=True)
        with open(abs_, "w", encoding="utf-8") as f:
            f.write(txt)
        written.append(rel)
        for src_root, dst_root in ((BACKEND, DESKTOP_BACKEND), (FRONTEND, DESKTOP_FRONTEND)):
            if rel.startswith(src_root) and os.path.isdir(os.path.join(ROOT, dst_root)):
                mirror = os.path.join(ROOT, dst_root + rel[len(src_root):])
                os.makedirs(os.path.dirname(mirror), exist_ok=True)
                with open(mirror, "w", encoding="utf-8") as f:
                    f.write(txt)
    print(f"   wrote {len(written)} files (backups: .bak-{FENCE})")
    with open(os.path.join(ROOT, f".{FENCE}.done"), "w") as f:
        f.write("applied\n")
    if SKIP_TESTS:
        print("   --skip-tests: done")
        return

    env = dict(os.environ, PYTHONPATH=os.path.join(ROOT, "backend"), SCALP_LOT_SIZE_OFFLINE="1")
    suites = [
        "app/backtest/engine/test_lot_comp_dd.py",
        "app/backtest/engine/test_lot_comp_equity.py",
        "app/backtest/engine/test_lot_comp_max.py",
        "app/backtest/engine/test_lot_compounding.py",
        "app/backtest/engine/test_lot_comp_runners.py",
    ]
    failed = []
    for s in suites:
        r = subprocess.run([sys.executable, s], cwd=os.path.join(ROOT, "backend"),
                           env=env, capture_output=True, text=True, timeout=1800)
        tail = (r.stdout.strip().splitlines() or [""])[-1]
        print(f"   {'ok  ' if r.returncode == 0 else 'FAIL'} {s}  — {tail[:100]}")
        if r.returncode != 0:
            failed.append(s)
            print((r.stdout + r.stderr)[-3000:])
    esb = (os.environ.get("ESBUILD") or
           (os.path.join(ROOT, "frontend", "node_modules", ".bin", "esbuild")
            if os.path.exists(os.path.join(ROOT, "frontend", "node_modules", ".bin", "esbuild")) else None) or
           shutil.which("esbuild") or ("npx" if shutil.which("npx") else None))
    if esb:
        for rel in [f"{FRONTEND}/Backtest.jsx", f"{FRONTEND}/backtest/SweepBuilder.jsx",
                    f"{FRONTEND}/backtest/lotCompounding.js"]:
            cmd = ([esb, "--yes", "esbuild"] if esb == "npx" else [esb])
            r = subprocess.run(cmd + [rel, "--loader:.jsx=jsx", "--loader:.js=jsx",
                                      "--log-level=error", "--outfile=/dev/null"],
                               cwd=ROOT, capture_output=True, text=True, timeout=300)
            print(f"   {'ok  ' if r.returncode == 0 else 'FAIL'} esbuild {rel}")
            if r.returncode != 0:
                failed.append(rel)
                print(r.stderr[-2000:])
    else:
        print("   (esbuild not found — skipping JSX parse; run ./desktop/build-scalp.sh both)")
    if failed:
        print("\n   FAILURES — rolling back to the .bak files:")
        for rel in written:
            abs_ = os.path.join(ROOT, rel)
            bak = abs_ + f".bak-{FENCE}"
            if os.path.exists(bak):
                shutil.move(bak, abs_)
            else:
                os.remove(abs_)
        try:
            os.remove(os.path.join(ROOT, f".{FENCE}.done"))
        except OSError:
            pass
        die("tests failed; working copy restored")
    print(f"\n── {FENCE} applied. Next: ./desktop/build-scalp.sh both ──")


if __name__ == "__main__":
    main()
