# backend/app/backtest/report/report_engine.py
#
# ── REPORT_ENGINE ── deterministic backtest report over a set of persisted
# runs. Every number in the output is COMPUTED here; nothing is estimated,
# summarised, or generated by a model. The Phase-3 LLM layer consumes the
# `summary` JSON this module returns and writes prose ONLY — it never touches
# arithmetic.
#
# DESIGN CONTRACT (deliberate):
#   * Pure module: no app.* imports, no DB access, no file I/O. Input is a
#     list of run dicts exactly as backtest_repo.get_run() returns them
#     ({run_id, strategy_id, date_from, date_to, config, summary, trades:[...]}).
#     The ROUTE loads runs and saves the file; this module only computes.
#     That keeps it unit-testable against synthetic trades with zero mocks.
#   * KPI math mirrors the UI's computeMetrics (Backtest.jsx): net-of-charges
#     per trade, ENTRY-ordered equity for drawdown — so report numbers
#     cross-check against the run's own Summary/Advanced tabs.
#   * Year slices use the ENTRY timestamp in IST (fixed +5:30, never runtime
#     TZ) — same convention as the UI Yearly tab. Valid to slice because all
#     supported strategies are intraday with EOD square-off and daily resets:
#     a year slice of a full-corpus run is identical to running that year
#     alone.
#   * Robust ranking (the anti-overfitting core): worst-year net first, then
#     profitable-years count, then median yearly Return÷DD — shown NEXT TO the
#     naive total-net ranking so divergence is visible. Sign-flip flag marks
#     configs whose recent year contradicts their history (the 2021-hero /
#     2026-casualty pattern).
#
# Sections: header · leaderboard · parameter sensitivity (config-diff based,
# label-independent) · year-by-year matrix · robust ranking · portfolio
# (auto when the selection is one run per strategy over one period) ·
# observations placeholder (Phase 3) · definitions appendix.

from __future__ import annotations

import json
from datetime import datetime, timedelta
from typing import Any, Dict, List, Optional, Tuple

IST_OFFSET = 5 * 3600 + 30 * 60

STRAT_SHORT = {
    "SCALP_V1": "V1", "SCALP_V3": "V3", "SCALP_V5": "V5",
    "HA_V1": "HA", "HA_SELL": "HAS", "WICK_V1": "WICK",
    "IC_V1": "IC", "TSG_V1": "TSG", "PST_V1": "PST", "PST_SELL": "PSTS", "PST_HEDGE": "PSTH",
    "BB_V1": "BB1", "BB_V2": "BB2",
}

# short display names for flattened config keys (fallback: the raw key)
AXIS_LABEL = {
    "risk_reward_ratio": "RR",
    "min_sl_points": "minSL",
    "max_sl_points": "maxSL",
    "risk_max_sl_points": "rMaxSL",
    "hedge_sl_points": "hSL",
    "sl_points": "SL",
    "tp_points": "TP",
    "tp_hold_extra_candles": "hold",
    "max_trades_per_side": "cap",
    "timeframe_minutes": "tf",
    "top_wick_min": "wick",
    "option_premium.min": "prem.min",
    "option_premium.max": "prem.max",
    "target_override.enabled": "tgt.on",
    "target_override.points": "tgt.pts",
    "entry_conditions": "conds",
    "session.primary.start": "sess.start",
    "session.primary.end": "sess.end",
    "trade_side_mode": "side",
    "quantity.lots": "lots",
    "max_loss": "maxLoss",
    "max_profit": "maxProfit",
    "dual_side_mode": "dualSide",
}


# ──────────────────────────────────────────────────────────────────────
# small pure helpers
# ──────────────────────────────────────────────────────────────────────
def _net(t: dict) -> float:
    if t.get("net_pnl") is not None:
        return float(t["net_pnl"])
    return float(t.get("pnl") or 0.0) - float(t.get("charges") or 0.0)


def _closed(trades: List[dict]) -> List[dict]:
    return [t for t in trades if t.get("exit_price") is not None]


def _ist_dt(epoch: int) -> datetime:
    return datetime(1970, 1, 1) + timedelta(seconds=int(epoch) + IST_OFFSET)


def _ist_year(epoch: int) -> int:
    return _ist_dt(epoch).year


def _median(vals: List[float]) -> Optional[float]:
    if not vals:
        return None
    s = sorted(vals)
    m = len(s) // 2
    return s[m] if len(s) % 2 else (s[m - 1] + s[m]) / 2.0


def _pearson(xs: List[float], ys: List[float]) -> Optional[float]:
    n = len(xs)
    if n < 2:
        return None
    mx = sum(xs) / n
    my = sum(ys) / n
    sxy = sxx = syy = 0.0
    for x, y in zip(xs, ys):
        dx, dy = x - mx, y - my
        sxy += dx * dy
        sxx += dx * dx
        syy += dy * dy
    if sxx == 0 or syy == 0:
        return None
    return sxy / (sxx * syy) ** 0.5


def _inr(v: Optional[float]) -> str:
    """Indian-grouped rupee string: 1234567 → ₹12,34,567 (sign preserved)."""
    if v is None:
        return "—"
    n = int(round(v))
    sign = "-" if n < 0 else ""
    s = str(abs(n))
    if len(s) > 3:
        head, tail = s[:-3], s[-3:]
        parts: List[str] = []
        while len(head) > 2:
            parts.insert(0, head[-2:])
            head = head[:-2]
        if head:
            parts.insert(0, head)
        s = ",".join(parts + [tail])
    return f"{sign}₹{s}"


def _rdd_str(v: Optional[float]) -> str:
    if v is None:
        return "—"
    if v == float("inf"):
        return "∞"
    return f"{v:.2f}"


def _md_table(headers: List[str], rows: List[List[str]]) -> str:
    out = ["| " + " | ".join(headers) + " |",
           "|" + "|".join("---" for _ in headers) + "|"]
    for r in rows:
        out.append("| " + " | ".join(str(x) for x in r) + " |")
    return "\n".join(out)


# ──────────────────────────────────────────────────────────────────────
# KPIs — mirrors the UI's computeMetrics (entry-ordered equity for DD)
# ──────────────────────────────────────────────────────────────────────
def kpis(trades: List[dict]) -> dict:
    closed = sorted(_closed(trades), key=lambda t: t.get("entry_ts") or 0)
    n = len(closed)
    if n == 0:
        return {"trades": 0, "net": 0.0, "gross": 0.0, "charges": 0.0,
                "wins": 0, "losses": 0, "win_rate": 0.0, "max_dd": 0.0,
                "profit_factor": None, "expectancy": None, "return_to_dd": None}
    nets = [_net(t) for t in closed]
    gross = sum(float(t.get("pnl") or 0.0) for t in closed)
    charges = sum(float(t.get("charges") or 0.0) for t in closed)
    total = sum(nets)
    wins = sum(1 for p in nets if p > 0)
    losses = sum(1 for p in nets if p < 0)
    gp = sum(p for p in nets if p > 0)
    gl = abs(sum(p for p in nets if p < 0))
    eq = peak = dd = 0.0
    for p in nets:
        eq += p
        if eq > peak:
            peak = eq
        if peak - eq > dd:
            dd = peak - eq
    pf = (gp / gl) if gl > 0 else (float("inf") if gp > 0 else None)
    rdd = (total / dd) if dd > 0 else (float("inf") if total > 0 else 0.0)
    return {
        "trades": n, "net": total, "gross": gross, "charges": charges,
        "wins": wins, "losses": losses, "win_rate": 100.0 * wins / n,
        "max_dd": dd, "profit_factor": pf,
        "expectancy": total / n, "return_to_dd": rdd,
    }


def year_slices(trades: List[dict]) -> Dict[int, dict]:
    """Per-IST-calendar-year KPIs, sliced by ENTRY timestamp (matches the UI
    Yearly tab). Valid as standalone-year results for intraday strategies
    with daily resets (no cross-day state)."""
    by_year: Dict[int, List[dict]] = {}
    for t in _closed(trades):
        if not t.get("entry_ts"):
            continue
        by_year.setdefault(_ist_year(t["entry_ts"]), []).append(t)
    return {y: kpis(ts) for y, ts in sorted(by_year.items())}


# ──────────────────────────────────────────────────────────────────────
# Config diff → shared baseline + varied axes (label-independent)
# ──────────────────────────────────────────────────────────────────────
def _flatten(v: Any, key: str = "") -> Dict[str, Any]:
    if isinstance(v, dict):
        out: Dict[str, Any] = {}
        for k in sorted(v):
            out.update(_flatten(v[k], f"{key}.{k}" if key else str(k)))
        return out
    if isinstance(v, list):
        return {key: json.dumps(v)}
    return {key: v}


def _axis_label(key: str) -> str:
    return AXIS_LABEL.get(key, key)


def _fmt_axis_value(key: str, v: Any) -> str:
    if v is None:
        return "—"
    if key == "entry_conditions" and isinstance(v, str):
        try:
            return "+".join(str(c).replace("COND", "C") for c in json.loads(v))
        except Exception:
            return str(v)
    return str(v)


def config_axes(runs: List[dict]) -> Tuple[Dict[str, Any], Dict[str, List[Any]]]:
    """Returns (shared, varied). shared: flat key → common value.
    varied: flat key → per-run value list (aligned with `runs` order)."""
    flats = [_flatten(r.get("config") or {}) for r in runs]
    keys = sorted({k for f in flats for k in f})
    shared: Dict[str, Any] = {}
    varied: Dict[str, List[Any]] = {}
    for k in keys:
        vals = [f.get(k) for f in flats]
        if len({json.dumps(v, sort_keys=True) for v in vals}) == 1:
            shared[k] = vals[0]
        else:
            varied[k] = vals
    return shared, varied


# ──────────────────────────────────────────────────────────────────────
# Per-run assembly + robust ranking
# ──────────────────────────────────────────────────────────────────────
def _run_label(run: dict, varied: Dict[str, List[Any]], idx: int) -> str:
    strat = STRAT_SHORT.get(run.get("strategy_id"), run.get("strategy_id") or "?")
    rid = (run.get("run_id") or "")[:8]
    parts = [f"{_axis_label(k)}={_fmt_axis_value(k, vals[idx])}"
             for k, vals in varied.items()]
    return f"{strat} {rid}" + (f" [{', '.join(parts)}]" if parts else "")


def robust_stats(years: Dict[int, dict]) -> dict:
    """Worst-year net, profitable-years count, median yearly Return÷DD, and
    the sign-flip flag: the most recent year's sign contradicts the combined
    sign of all prior years (edge died — or emerged)."""
    if not years:
        return {"worst_year_net": None, "worst_year": None,
                "profitable_years": 0, "total_years": 0,
                "median_year_rdd": None, "flip": False, "flip_note": ""}
    items = sorted(years.items())
    nets = {y: k["net"] for y, k in items}
    worst_year = min(nets, key=lambda y: nets[y])
    prof = sum(1 for v in nets.values() if v > 0)
    rdds = [k["return_to_dd"] for _, k in items
            if k["return_to_dd"] is not None and k["return_to_dd"] != float("inf")]
    med = _median(rdds)
    flip = False
    note = ""
    if len(items) >= 2:
        last_y, last_k = items[-1]
        prior = sum(k["net"] for y, k in items[:-1])
        if prior * last_k["net"] < 0:
            flip = True
            note = (f"edge died: prior {_inr(prior)} → {last_y} {_inr(last_k['net'])}"
                    if prior > 0 else
                    f"edge emerged: prior {_inr(prior)} → {last_y} {_inr(last_k['net'])}")
    return {"worst_year_net": nets[worst_year], "worst_year": worst_year,
            "profitable_years": prof, "total_years": len(items),
            "median_year_rdd": med, "flip": flip, "flip_note": note}


def _robust_sort_key(r: dict) -> tuple:
    rs = r["robust"]
    worst = rs["worst_year_net"] if rs["worst_year_net"] is not None else float("-inf")
    med = rs["median_year_rdd"]
    med = -1e18 if med is None else (1e18 if med == float("inf") else med)
    return (worst, rs["profitable_years"], med)


# ──────────────────────────────────────────────────────────────────────
# Sensitivity (per varied axis) + optional 2-axis grid matrix
# ──────────────────────────────────────────────────────────────────────
def _try_num(v: Any):
    try:
        return (0, float(v))
    except (TypeError, ValueError):
        return (1, str(v))


def sensitivity(varied: Dict[str, List[Any]], per_run: List[dict]) -> Dict[str, List[dict]]:
    """axis key → sorted groups [{value, runs, mean_net, best_net, mean_dd,
    mean_rdd}]. Grouped over ALL selected runs, so in a 2-axis grid each
    group is the MARGINAL over the other axis."""
    out: Dict[str, List[dict]] = {}
    for key, vals in varied.items():
        groups: Dict[str, dict] = {}
        for i, v in enumerate(vals):
            gk = json.dumps(v, sort_keys=True)
            g = groups.setdefault(gk, {"value": v, "nets": [], "dds": [], "rdds": []})
            k = per_run[i]["kpis"]
            g["nets"].append(k["net"])
            g["dds"].append(k["max_dd"])
            if k["return_to_dd"] is not None and k["return_to_dd"] != float("inf"):
                g["rdds"].append(k["return_to_dd"])
        rows = []
        for g in groups.values():
            n = len(g["nets"])
            rows.append({
                "value": g["value"], "runs": n,
                "mean_net": sum(g["nets"]) / n,
                "best_net": max(g["nets"]),
                "mean_dd": sum(g["dds"]) / n,
                "mean_rdd": (sum(g["rdds"]) / len(g["rdds"])) if g["rdds"] else None,
            })
        rows.sort(key=lambda r: _try_num(r["value"]))
        out[key] = rows
    return out


def grid_matrix(varied: Dict[str, List[Any]], per_run: List[dict]) -> Optional[dict]:
    """When exactly two axes vary: net-P&L matrix (axis1 rows × axis2 cols).
    Cell = net of that combo's run (mean if duplicated)."""
    if len(varied) != 2:
        return None
    (k1, v1s), (k2, v2s) = sorted(varied.items())
    cells: Dict[Tuple[str, str], List[float]] = {}
    for i in range(len(per_run)):
        cells.setdefault((json.dumps(v1s[i]), json.dumps(v2s[i])), []).append(
            per_run[i]["kpis"]["net"])
    rows = sorted({json.dumps(v) for v in v1s}, key=lambda s: _try_num(json.loads(s)))
    cols = sorted({json.dumps(v) for v in v2s}, key=lambda s: _try_num(json.loads(s)))
    matrix = [[(sum(cells[(r, c)]) / len(cells[(r, c)])) if (r, c) in cells else None
               for c in cols] for r in rows]
    return {"axis_rows": k1, "axis_cols": k2,
            "row_values": [json.loads(r) for r in rows],
            "col_values": [json.loads(c) for c in cols],
            "net_matrix": matrix}


# ──────────────────────────────────────────────────────────────────────
# Portfolio section (one run per strategy, single period) — exit-realized,
# same math as Portfolio.jsx composePortfolio
# ──────────────────────────────────────────────────────────────────────
def portfolio_section(runs: List[dict]) -> Optional[dict]:
    strategies = [r.get("strategy_id") for r in runs]
    periods = {(r.get("date_from"), r.get("date_to")) for r in runs}
    if len(runs) < 2 or len(set(strategies)) != len(runs) or len(periods) != 1:
        return None

    def _events(r):
        return sorted(((int(t["exit_ts"]), _net(t)) for t in _closed(r["trades"])
                       if t.get("exit_ts")), key=lambda e: e[0])

    per = []
    for r in runs:
        ev = _events(r)
        eq = peak = dd = 0.0
        for _, n in ev:
            eq += n
            if eq > peak:
                peak = eq
            if peak - eq > dd:
                dd = peak - eq
        daily: Dict[str, float] = {}
        for ts, n in ev:
            k = _ist_dt(ts).strftime("%Y-%m-%d")
            daily[k] = daily.get(k, 0.0) + n
        per.append({"strategy_id": r.get("strategy_id"), "run_id": r.get("run_id"),
                    "net": eq, "max_dd_exit": dd, "daily": daily})

    merged = sorted((e for r in runs for e in _events(r)), key=lambda e: e[0])
    eq = peak = dd = 0.0
    for _, n in merged:
        eq += n
        if eq > peak:
            peak = eq
        if peak - eq > dd:
            dd = peak - eq
    sum_dd = sum(p["max_dd_exit"] for p in per)

    corr = []
    for i in range(len(per)):
        for j in range(i + 1, len(per)):
            days = sorted(set(per[i]["daily"]) | set(per[j]["daily"]))
            r = _pearson([per[i]["daily"].get(d, 0.0) for d in days],
                         [per[j]["daily"].get(d, 0.0) for d in days])
            corr.append({"a": per[i]["strategy_id"], "b": per[j]["strategy_id"],
                         "r": r, "days": len(days)})
    return {"per_strategy": per, "combined_net": eq, "combined_max_dd": dd,
            "sum_individual_dd": sum_dd,
            "dd_reduction_pct": (100.0 * (1 - dd / sum_dd)) if sum_dd > 0 else None,
            "correlations": corr}


# ──────────────────────────────────────────────────────────────────────
# Report assembly
# ──────────────────────────────────────────────────────────────────────
def generate_report(runs: List[dict], title: str = "backtest-report",
                    generated_at_epoch: Optional[int] = None) -> dict:
    """runs: list of get_run() dicts. Returns {"markdown": str, "summary": dict}."""
    if not runs:
        raise ValueError("no runs given")
    now = generated_at_epoch if generated_at_epoch is not None else int(
        (datetime.utcnow() - datetime(1970, 1, 1)).total_seconds())
    shared, varied = config_axes(runs)

    per_run: List[dict] = []
    for i, r in enumerate(runs):
        k = kpis(r.get("trades") or [])
        yrs = year_slices(r.get("trades") or [])
        per_run.append({
            "run_id": r.get("run_id"), "strategy_id": r.get("strategy_id"),
            "date_from": r.get("date_from"), "date_to": r.get("date_to"),
            "label": _run_label(r, varied, i),
            "kpis": k, "years": {str(y): v for y, v in yrs.items()},
            "robust": robust_stats(yrs),
        })

    naive = sorted(range(len(per_run)), key=lambda i: per_run[i]["kpis"]["net"], reverse=True)
    robust = sorted(range(len(per_run)), key=lambda i: _robust_sort_key(per_run[i]), reverse=True)
    naive_rank = {i: n + 1 for n, i in enumerate(naive)}
    robust_rank = {i: n + 1 for n, i in enumerate(robust)}

    sens = sensitivity(varied, per_run)
    grid = grid_matrix(varied, per_run)
    pf = portfolio_section(runs)

    # ── markdown ────────────────────────────────────────────────────
    md: List[str] = []
    strategies = sorted({r.get("strategy_id") or "?" for r in runs})
    periods = sorted({f"{r.get('date_from')} → {r.get('date_to')}" for r in runs})
    md.append(f"# Backtest Report — {title}")
    md.append(f"Generated {_ist_dt(now).strftime('%Y-%m-%d %H:%M IST')} · "
              f"{len(runs)} runs · {', '.join(strategies)} · {'; '.join(periods)}")
    md.append("")

    md.append("## 1. Scope & Baseline")
    if varied:
        md.append("**Varied axes:** " + ", ".join(_axis_label(k) for k in sorted(varied)))
    else:
        md.append("**Varied axes:** none — all selected runs share one config.")
    if shared:
        md.append("")
        md.append("Shared baseline (identical across every run):")
        md.append(_md_table(["Param", "Value"],
                            [[_axis_label(k), _fmt_axis_value(k, v)]
                             for k, v in sorted(shared.items())]))
    md.append("")

    md.append("## 2. Leaderboard")
    md.append(_md_table(
        ["Run", "Net", "Max DD", "R÷DD", "PF", "Expect/trade", "Win %", "Trades"],
        [[p["label"], _inr(p["kpis"]["net"]), _inr(p["kpis"]["max_dd"]),
          _rdd_str(p["kpis"]["return_to_dd"]),
          _rdd_str(p["kpis"]["profit_factor"]),
          _inr(p["kpis"]["expectancy"]) if p["kpis"]["expectancy"] is not None else "—",
          f"{p['kpis']['win_rate']:.1f}%", p["kpis"]["trades"]]
         for p in (per_run[i] for i in naive)]))
    md.append("")

    md.append("## 3. Parameter Sensitivity")
    if not sens:
        md.append("Single config — nothing varied.")
    for key, rows in sens.items():
        md.append(f"### {_axis_label(key)}")
        md.append(_md_table(
            ["Value", "Runs", "Mean net", "Best net", "Mean DD", "Mean R÷DD"],
            [[_fmt_axis_value(key, r["value"]), r["runs"], _inr(r["mean_net"]),
              _inr(r["best_net"]), _inr(r["mean_dd"]), _rdd_str(r["mean_rdd"])]
             for r in rows]))
        md.append("")
    if grid:
        md.append(f"### Grid — net P&L: {_axis_label(grid['axis_rows'])} (rows) × "
                  f"{_axis_label(grid['axis_cols'])} (cols)")
        headers = [_axis_label(grid["axis_rows"])] + \
            [_fmt_axis_value(grid["axis_cols"], c) for c in grid["col_values"]]
        rows = []
        for ri, rv in enumerate(grid["row_values"]):
            rows.append([_fmt_axis_value(grid["axis_rows"], rv)] +
                        [_inr(c) if c is not None else "—"
                         for c in grid["net_matrix"][ri]])
        md.append(_md_table(headers, rows))
        md.append("")

    md.append("## 4. Year-by-Year (net P&L, entry-time IST)")
    all_years = sorted({y for p in per_run for y in p["years"]})
    if all_years:
        rows = []
        for p in per_run:
            rows.append([p["label"]] +
                        [_inr(p["years"][y]["net"]) if y in p["years"] else "—"
                         for y in all_years])
        md.append(_md_table(["Run"] + all_years, rows))
    else:
        md.append("No closed trades.")
    md.append("")

    md.append("## 5. Robust Ranking (worst-year first)")
    md.append("Primary: worst-year net · tiebreaks: profitable years, median "
              "yearly R÷DD. A config that never had a bad year beats a config "
              "with a bigger total built on one golden regime.")
    md.append("")
    rows = []
    for n, i in enumerate(robust):
        p = per_run[i]
        rs = p["robust"]
        rows.append([
            n + 1, p["label"], _inr(p["kpis"]["net"]),
            f"{_inr(rs['worst_year_net'])}" + (f" ({rs['worst_year']})" if rs["worst_year"] else ""),
            f"{rs['profitable_years']}/{rs['total_years']}",
            _rdd_str(rs["median_year_rdd"]),
            f"⚠ FLIP — {rs['flip_note']}" if rs["flip"] else "",
            naive_rank[i],
        ])
    md.append(_md_table(
        ["Rank", "Run", "Total net", "Worst year", "Prof. years",
         "Median yr R÷DD", "Flag", "Naive rank"], rows))
    if robust and naive and robust[0] != naive[0]:
        md.append("")
        md.append(f"**Naive-vs-robust divergence:** total net ranks "
                  f"{per_run[naive[0]]['label']} first, but the robust winner is "
                  f"{per_run[robust[0]]['label']} — the naive champion's total is "
                  f"built on years the robust metrics penalize.")
    diverging = [per_run[i]["label"] for i in robust[:3]
                 if naive_rank[i] > 3 and len(per_run) > 3]
    if diverging:
        md.append("")
        md.append("Also in the robust top 3 despite a weak naive rank: " +
                  "; ".join(diverging) + ".")
    md.append("")

    if pf:
        md.append("## 6. Portfolio (composition, exit-realized)")
        md.append(_md_table(
            ["Strategy", "Net", "Own Max DD (exit)"],
            [[STRAT_SHORT.get(p["strategy_id"], p["strategy_id"]),
              _inr(p["net"]), _inr(p["max_dd_exit"])] for p in pf["per_strategy"]]))
        md.append("")
        md.append(f"Combined net {_inr(pf['combined_net'])} · combined Max DD "
                  f"{_inr(pf['combined_max_dd'])} · Σ individual DD "
                  f"{_inr(pf['sum_individual_dd'])} · **DD reduction "
                  f"{pf['dd_reduction_pct']:.1f}%**"
                  if pf["dd_reduction_pct"] is not None else
                  f"Combined net {_inr(pf['combined_net'])}")
        if pf["correlations"]:
            md.append("")
            md.append(_md_table(
                ["Pair", "Daily-net correlation", "Days"],
                [[f"{STRAT_SHORT.get(c['a'], c['a'])} × {STRAT_SHORT.get(c['b'], c['b'])}",
                  "—" if c["r"] is None else f"{c['r']:.2f}", c["days"]]
                 for c in pf["correlations"]]))
        md.append("")

    md.append("## 7. Observations")
    md.append("_(narrative layer — Phase 3; every number above is computed, "
              "none is generated)_")
    md.append("")
    md.append("## Appendix — Definitions")
    md.append("Net = per-trade net of charges. Max DD = peak-to-trough of the "
              "entry-ordered net equity (matches the UI Advanced tab). Year "
              "slices by entry time, IST (+5:30 fixed) — valid standalone since "
              "all strategies are intraday with daily resets. Portfolio DD is "
              "exit-realized (P&L booked at exit_ts). Sensitivity groups are "
              "marginals over the other varied axes.")

    summary = {
        "title": title,
        "generated_at": now,
        "strategies": strategies,
        "periods": periods,
        "shared_baseline": {k: _fmt_axis_value(k, v) for k, v in shared.items()},
        "varied_axes": sorted(varied.keys()),
        "runs": per_run,
        "sensitivity": {k: [{**r, "value": _fmt_axis_value(k, r["value"])}
                            for r in rows] for k, rows in sens.items()},
        "grid": grid,
        "ranking": {
            "robust_order": [per_run[i]["run_id"] for i in robust],
            "naive_order": [per_run[i]["run_id"] for i in naive],
        },
        "portfolio": pf,
    }
    return {"markdown": "\n".join(md), "summary": summary}