class TradeSafety:
    def handle_order_failure(self, order_id, reason): ...
    def handle_partial_fill(self, order_id): ...
    def verify_oco(self, parent_order_id) -> bool: ...
    def sync_on_startup(self): ...
